export const COPY = {
  fr: {
    langue: "fr",

    /* Onglets — ils ont leur propre version, ils ne se traduisent pas mot à mot */

    /* Accueil — la phrase se compose selon la situation, et reste juste
       dans tous les cas. Voir spec 3.2. */
    salut: (prenom) => "Bonjour, " + prenom,
    etatRien: "Rien dans les semaines qui viennent.",
    etatUnAujourdhui: "Une date aujourd'hui.",
    etatUnSemaine: "Une date cette semaine.",
    etatDeuxSemaine: "Deux dates cette semaine.",
    etatPlusieursSemaine: (n) => n + " dates cette semaine.",
    etatUnAujourdhuiEtSemaine: (n) => n === 1
      ? "Une date aujourd'hui, une autre cette semaine."
      : "Une date aujourd'hui, " + n + " autres cette semaine.",
    etatLointain: (date) => "Rien avant le " + date + ".",

    ceQuiApproche: "Ce qui approche",
    plusTard: "Plus tard",
    preparer: "Préparer",
    marquerEnvoye: "Marquer envoyé",
    laisserNote: "Laisser une note",
    ajouterAnniversaire: "Ajouter un anniversaire",
    voirTout: "Voir tout",
    moisPrecedent: "Mois précédent",
    moisSuivant: "Mois suivant",
    voirPlus: "Voir plus",
    prochesReste: (n) => "Voir plus · " + n + " restants",
    prochesCompte: (n) => n + " proches",
    ficheSousTitre: "Anniversaire · 24 août · amical",

    /* Le décompte — deux notations à l'essai. Le test utilisateur tranchera ;
       aucune des deux n'est écrite dans un composant. */
    decompteBarre: (n) => "J−" + n,
    decomptePhrase: (n) => n === 1 ? "dans 1 jour" : "dans " + n + " jours",

    /* L'invitation de l'accueil — elle ne vit que tant qu'aucune liste n'existe. */
    accueilFaireListe: "Faire ma wishlist",
    accueilFaireListeSous: "Vos proches sauront quoi vous offrir.",

    videCarnetTitre: "Votre carnet est prêt",
    videCarnetTexte: "Ajoutez un premier proche et sa date. Lehno s'occupe de vous le rappeler.",
    videRienTitre: "Rien dans les semaines qui viennent",
    videRienTexte: "Le bon moment pour noter une idée pendant qu'elle est fraîche.",

    /* Proches */
    prochesTitre: "Vos proches",
    rechercher: "Rechercher un proche",
    triDate: "Par date", triDateProche: "au plus proche", triDateLoin: "au plus loin",
    triAlphaAZ: "A–Z", triAlphaZA: "Z–A", triAlpha: "A → Z",
    ajouterProche: "Ajouter un proche",
    completer: "Compléter",
    videAnnuaireTitre: "Personne dans le carnet",
    videAnnuaireTexte: "Ajoutez un proche et sa date. Le reste se remplit au fil de l'année.",

    /* Types d'événement */
    typeAnniversaire: "Anniversaire", typeMariage: "Mariage", typeRetraite: "Retraite",
    typeNaissance: "Naissance", typeEtape: "Étape", typeFete: "Fête", typeAutre: "Autre",
    aujourdhui: "aujourd'hui",

    /* Notes */

    /* Réseau et attente */
    horsConnexion: "Hors connexion. Vos notes et vos dates restent consultables.",
    horsConnexionFile: (n) => n === 1
      ? "Hors connexion. Une action repartira au retour du réseau."
      : "Hors connexion. " + n + " actions repartiront au retour du réseau.",
    chargement: "Chargement",

    /* ─── Connexion (3.1) ─── */
    ongletAccueil: "Accueil", ongletDates: "Dates", ongletProches: "Proches",
    ongletMoi: "Moi", ongletReglages: "Réglages",







    /* ─── Mon Mur côté privé (3.10), profil, réglages, sécurité, aide ─── */
    murPrivAdresse: "lehno.app/valentine",
    murPrivPublie: "Publié",
    murPrivPrive: "Hors ligne",
    murPrivBascule: "Rendre mon Mur public",
    murPrivExpose: "Ce qui est exposé",
    murPrivGouts: "Mes goûts",
    murPrivDate: "Ma date d'anniversaire",
    murPrivSouhaits: "Ma wishlist",
    murPrivMots: "Les mots reçus",
    murPrivMotsCompte: (n) => n === 1 ? "1 mot reçu" : n + " mots reçus",
    murPrivVoir: "Voir ma page",
    murPrivApercu: "Aperçu de ma page",
    murPrivCopier: "Copier le lien",
    murPrivCopie: "Lien copié",
    murPrivEpingler: "Épingler",
    murPrivEpingle: "Épinglé",
    murPrivDetacher: "Détacher",
    murPrivEpinglesAide: "Un mot épinglé s'affiche sur votre Mur. Les autres ne sortent pas d'ici.",
    murPrivMotsListe: [
      { texte: "Trente-quatre ans et toujours la première à danser. Ne change rien.", auteur: "Célarine", quand: "il y a deux jours" },
      { texte: "Bon anniversaire — cette année encore, tu as tenu tout le monde debout.", auteur: "Awa", quand: "il y a deux jours" },
      { texte: "Merci pour l'année dernière. Tu sais pourquoi.", auteur: null, quand: "il y a trois jours" }
    ],
    murPrivSansNom: "Sans nom",
    murPrivRienExpose: "Choisissez ce que vos proches verront.",
    murPrivAucunMotTitre: "Personne n'a encore écrit",
    murPrivAucunMotTexte: "Les mots que vos proches déposeront s'afficheront ici.",

    profilPhoto: "Changer la photo",
    champPrenom: "Prénom",
    profilNaissance: "Ma date d'anniversaire",
    profilNaissanceAide: "Elle apparaît sur mon Mur si je l'y expose.",
    profilGouts: "Mes goûts et intérêts",
    profilGoutsAide: "Un mot, une virgule, un autre mot.",
    profilGoutsExemple: "jazz, céramique, randonnée",
    champLangue: "Langue de l'interface",
    profilLangueAide: "Elle change tout de suite.",

    reglagesQuand: "Quand vous prévenir",
    reglagesJ7: "Une semaine avant",
    reglagesJ1: "La veille",
    reglagesJour: "Le jour même",
    reglagesComment: "Par quel moyen",
    reglagesPush: "Notification",
    reglagesEmail: "E-mail",
    reglagesRefus: "Les notifications sont refusées au niveau du téléphone. Les rappels partent par e-mail.",
    reglagesActiver: "Activer dans les réglages du téléphone",
    reglagesHeure: "L'heure d'envoi",
    reglagesHeures: ["7 h", "12 h", "18 h", "21 h"],
    reglagesAutres: "Le reste",
    reglagesRecap: "Le récapitulatif",
    reglagesRecapFreq: ["Chaque lundi", "Le 1er du mois"],
    reglagesValider: "Les contributions à valider",
    reglagesRelances: "Une date approche et rien n'est prêt",
    reglagesVieCompte: "Un mouvement sur vos crédits",
    reglagesSecuriteToujours: "Les alertes de sécurité vous parviennent quoi qu'il arrive.",
    reglagesMuet: "Aucun canal n'est ouvert : rien ne vous parviendra.",

    securiteMoyens: "Vos moyens de connexion",
    securiteAppareils: "Appareils connectés",
    securiteCetAppareil: "Cet appareil",
    securiteDeconnecterTout: "Déconnecter les autres appareils",
    securiteSupprimer: "Supprimer mon compte",
    securiteSupprimerAide: "Vos fiches, vos notes et votre Mur partent avec.",
    securiteInhabituelle: "Une connexion inhabituelle a été détectée le 12 août.",

    paiementAucuneTitre: "Aucune méthode enregistrée",
    paiementAucuneTexte: "Elle s'enregistrera d'elle-même au premier achat.",
    paiementAjouter: "Ajouter une méthode",
    paiementExpire: "Expirée",
    paiementDefaut: "Par défaut",
    paiementAjoutTitre: "Une méthode de plus",
    paiementNumero: "Le numéro mobile money",
    paiementCarteNum: "Le numéro de carte",
    paiementCarteExp: "Expire",
    paiementParDefaut: "En faire ma méthode par défaut",
    paiementAjoutFait: "Méthode enregistrée.",

    aideQuestions: "Questions fréquentes",
    aideContact: "Nous écrire",
    aideNoter: "Noter l'application",
    aideVersion: "Version",

    reservIntro: "Les cadeaux que vous vous êtes réservés sur le Mur de vos proches.",
    reservVideTitre: "Aucune réservation",
    reservVideTexte: "Ce que vous réserverez sur un Mur apparaîtra ici.",
    reservRetire: "Retiré par son propriétaire",
    reservLiberer: "Libérer",

    /* ─── Moi (3.17), crédits (3.9), parrainage ─── */
    feuilleCout: "Coût de l'action",
    feuilleLancer: "Lancer",
    feuilleRecharger: "Recharger",
    feuillePasMaintenant: "Pas maintenant",
    creditUnite: (n) => n + (n <= 1 ? " crédit" : " crédits"),
    creditReste: (n) => "il vous en reste " + n + (n <= 1 ? " crédit" : " crédits"),
    creditDepense: (n) => n + (n <= 1 ? " crédit dépensé" : " crédits dépensés"),
    creditMot: (n) => n <= 1 ? "crédit" : "crédits",
    moiCreditsSection: "Crédits",
    moiPresence: "Ma présence publique",
    moiCompte: "Mon compte",
    moiAide: "Aide",
    moiSolde: "Votre solde",
    moiRecharger: "Recharger",
    moiMonMur: "Mon Mur",
    moiMurVisible: "Visible par toute personne ayant le lien",
    moiMurDesactive: "Rien n'est public pour l'instant",
    moiReservations: "Mes réservations",
    moiProfil: "Mon profil",
    moiSecurite: "Sécurité et connexions",
    moiPaiement: "Méthodes de paiement",
    moiReglages: "Rappels et notifications",
    moiLangue: "Langue",
    moiAideCentre: "Questions et contact",
    moiDeconnexion: "Se déconnecter",

    /* Moi (3.17) — ce que je montre de moi. Du contenu, qui se partage. */
    moiSous: "Ce que vous montrez de vous.",
    moiPartager: "Partager",
    moiListes: "Mes wishlists",
    moiListesAucune: "Aucune wishlist pour l'instant",
    moiListesUne: "1 wishlist",
    moiListesN: (n) => n + " wishlists",
    moiLienVoeux: "Mon lien de vœux",
    moiLienVoeuxOuvert: "Jusqu'au 3 sept.",
    moiLienVoeuxFerme: "Fermé",
    moiMotsRecus: "Les mots reçus",
    moiMotsAucun: "Aucun mot",
    moiMotsN: (n) => n + " mots",
    moiCreerListe: "Créer une liste",
    listeApercu: "Voir et partager",
    pubListeTitre: (qui) => "La wishlist de " + qui,
    pubListeQuand: (date) => "Pour le " + date,
    pubListeReserver: "Réserver",
    pubListeReserve: "Réservé",
    pubListeDiscret: (qui) => qui + " ne voit pas qui réserve.",
    pubListeSansCompte: "Réserver ne demande aucun compte.",
    pubReserveFait: "Réservé, sans que ça se sache.",
    portraitApprouveFait: "Portrait approuvé.",
    portraitJeteFait: "Portrait jeté.",
    portraitEnregistreFait: "Image enregistrée.",
    collecteReactiveFait: "Lien réactivé.",
    collecteMot: (qui) => "Un mot pour " + qui,
    collecteMotAide: "Il s'affiche en haut de la page qu'on ouvrira.",
    collecteMotExemple: "ex. dis-moi ce qui te ferait plaisir, je m'occupe du reste",
    collecteApercu: "Voir la page avant d'envoyer",
    collecteRevoqueFait: "Lien révoqué.",
    lienCopieFait: "Lien copié.",
    murVoirDehors: "La page s'ouvre dans le navigateur.",
    reservLibereFait: "Réservation libérée.",
    securiteDeconnecteFait: "Les autres appareils sont déconnectés.",
    securiteSupprimeDemande: "Un e-mail confirme la suppression.",
    rappelsActivesFait: "Notifications activées.",
    photoMiseAJour: "Photo mise à jour.",
    souhaitModifieFait: "Souhait enregistré.",
    ficheSupprimeeFait: "Fiche supprimée.",
    lienOuvreDehors: "Le lien s'ouvre dans le navigateur.",
    pubListeInvite: "Tenir la mienne",
    listeCreer: "Nouvelle wishlist",
    listeSansDate: "Sans date",
    videListesTitre: "Aucune wishlist",
    videListesTexte: "Ouvrez-en une pour ranger ce qui vous ferait plaisir.",
    listeNouvNom: "Le nom de la liste",
    listeNouvNomExemple: "ex. mon anniversaire, la crémaillère",
    listeNouvOccasion: "L'occasion",
    listeNouvSansOccasion: "Sans occasion",
    listeNouvSansOccasionAide: "Elle vaut d'une année sur l'autre.",
    listeNouvDate: "Choisir une de mes dates",
    listeNouvCloture: "Fermer la liste après la date",
    listeNouvFait: "Wishlist créée.",
    souhaitModifierTitre: "Modifier le souhait",
    souhaitModifieEnregistre: "Souhait modifié.",
    murPrivOngletPage: "Ma page",
    murPrivOngletMots: (n) => n === 0 ? "Les mots" : "Les mots · " + n,
    reservOffert: "Marquer comme offert",
    reservOffertFait: "Noté comme offert.",
    reservDejaOffert: "Offert",
    moiPublierMur: "Publier mon Mur",
    moiVitrine: "Ce que vous partagez",
    moiRetour: "Ce qui en revient",

    /* Réglages (3.28) — ce qui me concerne. De la configuration, qu'on ouvre rarement. */
    reglagesTitre: "Réglages",
    reglagesArgent: "Crédits et paiements",
    reglagesCompte: "Mon compte",
    reglagesAlertes: "Rappels et données",
    reglagesAide: "Aide",
    moiRappels: "Rappels et notifications",
    moiDonnees: "Mes données",
    moiDonneesValeur: "Exporter, supprimer",

    /* ─── Mes données (3.30) ─── */
    donneesExport: "Demander une copie",
    donneesExportAide: "Vos fiches, vos notes, vos dates et vos souhaits, dans un fichier.",
    donneesExportFait: "Demande enregistrée.",
    donneesExportDemande: "Le fichier vous parvient par e-mail dans les 24 heures.",
    donneesCollecte: "Ce que Lehno garde",
    donneesCollecteTexte: "Ce que vous écrivez, et les dates que vous posez. Rien d'autre n'est lu.",

    /* ─── Fermer son compte, en trois temps ─── */
    supprTitre: "Fermer mon compte",
    supprPas: (n) => n + " sur 3",
    supprCeQuiPart: "Ce qui part avec",
    supprListe: ["Vos proches et tout ce que vous avez noté sur eux",
      "Vos dates et les rappels qui vont avec",
      "Vos wishlists, votre Mur et les mots reçus",
      "Les liens que vous avez partagés — ils cesseront de répondre"],
    supprCeQuiReste: "Ce que d'autres ont réservé chez eux ne bouge pas.",
    supprSolde: (n) => n <= 1 ? "Il vous reste " + n + " crédit." : "Il vous reste " + n + " crédits.",
    supprSoldeRemboursable: "Le solde vous est remboursé sur le moyen de paiement enregistré.",
    supprSoldeVide: "Vous n'avez plus de crédit à rembourser.",
    supprRaison: "Ce qui vous fait partir",
    supprRaisonFacultatif: "Facultatif.",
    supprRaisons: ["Je n'en ai plus besoin", "Trop cher", "Ça ne m'a pas servi",
      "Je recommencerai plus tard"],
    supprRaisonAutre: "Autre chose ?",
    supprConfirmer: "Pour finir",
    supprPseudo: "Votre pseudo",
    supprCode: "Le code envoyé par SMS",
    supprCodeRenvoyer: "Renvoyer le code",
    supprCodeRenvoye: "Code renvoyé.",
    supprSuivant: "Continuer",
    supprFermer: "Fermer mon compte",
    supprRenoncer: "Renoncer",
    supprFait: "Votre compte est fermé.",
    supprRevenir: "Revenir à Lehno",
    supprGrace: "Trente jours pour revenir : écrivez à bonjour@lehno.cm depuis cette adresse. Après, tout est effacé.",

    /* ─── État de lancement (drapeaux éteints) ─── */
    versementTitre: "Le versement",
    versementTexte: "Versez le montant sur ce numéro, puis déposez le reçu.",
    versementCompte: "Le compte Lehno",
    versementNumero: "+237 6 91 00 00 00",
    versementCopier: "Copier le numéro",
    versementCopieFait: "Numéro copié.",
    versementRecu: "Déposer mon reçu",
    versementRecuFait: "Reçu reçu. Le crédit est posé sous 24 heures.",
    versementDelai: "Le crédit est posé sous 24 heures.",
    mouvementsTitre: "Les mouvements",
    mouvementsAucun: "Aucun mouvement pour l'instant.",
    evtTitreAnniv: "Nouvel anniversaire",
    cartNoter: "Noter une idée",
    occNoterPour: (date) => "Noter une idée pour le " + date,

    rechargeTitre: "Combien de crédits ?",
    rechargeIntro: "Un crédit par contenu créé pour vous.",
    rechargeUnite: (n) => n === 1 ? "1 crédit" : n + " crédits",
    rechargeEconomie: (p) => "−" + p + " %",
    rechargeAttenteEnCours: "En attente",
    rechargeAttenteSecours: "Si rien ne s'affiche, composez le code de votre opérateur :",
    rechargeRecapTitre: "Avant de payer",
    rechargeRecapCredits: "Crédits",
    rechargeRecapMontant: "Montant",
    rechargeRecapFrais: (v) => "frais " + v,
    rechargeRecapTotal: "Total à payer",
    rechargeRecapModifier: "Changer de palier",
    rechargeMoyen: "Comment payer",
    rechargeMobile: "Mobile money",
    rechargeCarte: "Carte bancaire",
    rechargePayer: (m) => "Payer " + m,
    rechargeAttenteTitre: "Confirmez sur votre téléphone",
    rechargeAttenteTexte: "Une demande s'affiche sur votre téléphone. Comptez une à deux minutes.",
    rechargeAttenteExpire: "Sans validation, la demande expire d'elle-même.",
    rechargeAttenteFermer: "Fermer",
    rechargeAboutiTitre: "Crédits ajoutés",
    rechargeAboutiTexte: (n) => n + " crédits sont sur votre compte.",
    rechargeEchecTitre: "Le paiement n'a pas abouti",
    rechargeEchecTexte: "Rien n'a été prélevé.",

    parrainageTitre: "Invitez, et gagnez tous les deux",
    parrainageTexte: "Votre code donne 2 crédits à qui s'inscrit, et 2 crédits à vous.",
    parrainageCode: "VAL-4KX2",
    parrainagePartager: "Partager mon code",
    parrainageFilleuls: (n) => n === 1 ? "Une personne a utilisé votre code" : n + " personnes ont utilisé votre code",
    parrainageAucun: "Personne encore.",

    /* ─── Fiche d'un proche (3.4) et Dates (3.14) ─── */
    procheNotes: (n) => n === 1 ? "1 note" : n + " notes",
    procheAucuneNote: "Rien de noté encore",
    procheProchaine: (quoi, date) => quoi + " le " + date,
    ficheInterets: "Intérêts et goûts",
    ficheNotes: "Ce que vous avez noté",
    categories: { gout: "Goût", idee: "Idée", nogo: "À éviter", souvenir: "Souvenir", aclasser: "À classer" },
    reclasserAria: (l) => "Reclasser — actuellement : " + l,
    noteTitreModifier: "Modifier la note",
    noteSupprimer: "Supprimer cette note",
    noteIdee: "Idée",
    noteEviter: "À éviter",
    ficheIdees: "Idées cadeaux",
    ficheNogo: "Ce qu'il faut éviter",
    ficheNogoTexte: "Je ne bois pas d'alcool.",
    ficheIdeeTexte: "Valery a parlé d'un moulin à café manuel — le précédent rend l'âme.",
    fichePreparer: (date) => "Préparer le " + date,
    ficheAjouterNote: "Ajouter une note",
    ficheAjouterDate: "Ajouter une date",
    fichePortraits: "Ses portraits",
    ficheCollecte: "Faire compléter la fiche",
    ficheIdentite: "Modifier l'identité",
    ficheGoutsReste: (n) => "+" + n + " autres",
    ficheCollecteCourt: "Faire compléter", ficheIdentiteCourt: "Identité", fichePortraitsCourt: "Portraits",
    datesTitre: "Vos dates", ajouterDate: "Ajouter une date", vueListe: "Liste", vueCalendrier: "Calendrier",
    joursCourts: ["L", "M", "M", "J", "V", "S", "D"],
    calendrierAout: "Août 2026", calendrierRien: "Rien ce jour-là.",
    moisAout: "Août", moisSept: "Septembre",
    moisCourant: "Mois en cours",
    videDatesTitre: "Aucune date posée",
    videDatesTexte: "Posez la première : un anniversaire, un départ, un anniversaire de mariage.",

    /* ─── Lien de collecte (3.20) ─── */
    collecteTitre: "Laissez Valery compléter",
    collecteIntro: "Envoyez ce lien : ce qui en revient passe par votre validation avant d'entrer dans la fiche.",
    collecteLien: "lehno.app/c/8Kd2p",
    collectePartager: "Partager le lien",
    collecteCopier: "Copier le lien",
    collecteRevoquer: "Révoquer le lien",
    collecteReactiver: "Réactiver un lien",
    collecteEtatActif: "Actif",
    collecteEtatRevoque: "Révoqué",
    collecteRecu: (n) => n === 1 ? "Une réponse reçue" : n + " réponses reçues",
    collecteAucune: "Aucune réponse pour l'instant.",
    collecteRevoqueTexte: "Ce lien ne mène plus à rien. Vous pouvez en créer un autre.",

    /* ─── Identité d'un proche (3.18) ─── */
    identiteTitre: "Ce que Lehno doit savoir",
    identiteIntro: "Ces quelques éléments orientent ce que Lehno écrit.",
    champAppelle: "Comment vous l'appelez",
    champAppelleAide: "C'est ce nom qui apparaît dans les messages — « Maman », « mon vieux ».",
    champRelation: "Le lien",
    relFamilleProche: "Famille proche", relFamilleEtendue: "Famille étendue",
    relAmi: "Ami", relPartenaire: "Partenaire", relCollegue: "Collègue",
    relPro: "Relation pro", relConnaissance: "Connaissance",
    champRelationHint: "Où vous vous êtes connus",
    champRelationHintAide: "Une phrase suffit : « on s'est connus à la fac ».",
    registreFamilier: "Familier", registreFormel: "Formel",
    champVille: "Ville", champVilleAide: "Pour suggérer des adresses et des sorties.",
    champCanal: "Par où vous lui écrivez",
    champCanalAide: "Oriente la longueur du message proposé.",
    canalWhatsapp: "WhatsApp", canalSms: "SMS", canalEmail: "E-mail", canalAutre: "Autre",
    evtLabel: "Le libellé",
    evtLabelAide: "Tel que vous l'écrivez : il s'affichera sans traduction.",
    evtNatureSensible: "Sensible",
    champNom: "Nom",
    champLien: "Votre lien",
    champRegistre: "Registre",
    registreAmical: "Amical",
    registreFamilial: "Familial",
    registreRespectueux: "Respectueux",
    registreComplice: "Complice",
    identiteRegistreAide: "Le ton des messages proposés.",
    champLangueProche: "Langue des messages",
    identiteSupprimer: "Supprimer cette fiche",
    identiteSupprimerAide: "Ses notes et ses dates partent avec.",

    /* ─── Portrait, aperçu et partage (3.22) ─── */
    portraitAValider: "À valider",
    portraitApprouver: "Approuver",
    portraitSignature: "Votre note en pied",
    portraitSignatureAide: "« Fait avec soin par Valentine », sous le message. Le logotype, lui, reste toujours.",
    portraitAucunTitre: "Aucun portrait pour l'instant",
    portraitAucunTexte: "Le premier viendra de ce que vous avez noté.",

    /* ─── Reprises en cours (3.16) ─── */
    reprisesIntro: "Rien ne se perd. Ce que vous avez lancé vous attend ici.",
    reprisesVideTitre: "Tout est traité",
    reprisesVideTexte: "Ce que vous commencerez sans finir vous attendra ici.",
    repriseBrouillon: "Brouillon de message",
    repriseIdees: "Idées de cadeau",
    reprisePortrait: "Portrait",
    repriseDepassee: "La date est passée",
    repriseReprendre: "Reprendre",

    /* ─── Surfaces publiques dans l'app (3.12) ─── */
    pubRevoqueTexte: "Demandez un nouveau lien à qui vous l'a envoyé.",
    pubCollectePlaceholder: "ex. son anniversaire est le 22 mars, et la céramique est une passion",
    murGoutsLabel: (qui) => "Ce que " + qui + " aime",
    murSouhaitsLabel: "Ce qui lui ferait plaisir",
    murListeCta: "Voir sa wishlist",
    murMotLabel: "Les mots reçus",
    murMotExemple: (qui) => "Bon anniversaire " + qui + " — cette année encore, tu as tenu tout le monde debout.",
    murMotCta: "Laisser un mot",
    pubCollecteQui: (qui) => qui + " prépare quelque chose pour vous.",
    pubCollecteAvis: "Ce que vous laissez ici passe par sa validation avant d'entrer dans sa fiche.",
    pubCollecteDate: "Votre date",
    pubCollecteDateAide: "Le jour et le mois suffisent.",
    pubCollecteSouhaits: "Ce qui vous ferait plaisir",
    pubCollecteSouhaitsAide: "Une idée par ligne. Rien d'obligatoire.",
    pubCollecteSouhaitsPlaceholder: "ex. un moulin à café manuel",
    pubCollecteMot: "Un mot pour Valentine",
    pubCollecteMotPlaceholder: "ex. merci de penser à moi",
    pubCollecteAjouter: "Ajouter un souhait",
    pubCollecteChamp: "Ce que vous voulez lui dire",
    pubCollecteAide: "Sa date, ce qui lui ferait plaisir, un mot — ce que vous voulez.",
    pubReconnu: (qui) => "Vous êtes connecté comme " + qui + ".",
    pubSansCompte: "Répondre ne demande aucun compte.",
    pubMurSansCompte: "Laisser un mot ne demande aucun compte.",
    pubMurTitre: (qui) => "Le Mur de " + qui,
    pubCollecteTitre: "Valentine vous invite à remplir ce qui l'aidera",
    pubVoeuTitre: (qui) => "Laissez un mot à " + qui,
    pubVoeuChamp: "Votre message",
    pubVoeuPlaceholder: "ex. bon anniversaire — cette année encore, tu as tenu tout le monde debout",
    pubQui: "Votre nom (facultatif)",
    pubQuiAide: "Sans nom, votre mot arrive anonyme.",
    pubEnvoyer: "Envoyer",
    pubEnvoye: "C'est envoyé. Célarine le verra.",
    pubInviteTitre: "Et pour vos dates ?",
    pubInviteTexte: "Lehno retient les dates qui comptent et ce que vous savez de vos proches.",
    pubInviteAction: "Créer mon espace",
    pubInvitePlusTard: "Pas maintanant",
    pubRevoque: "Ce lien n'est plus valable.",
    pubVoeuxClos: "La fenêtre est fermée. Célarine a déjà reçu ses mots.",
    pubMurPrive: "Célarine n'a rien rendu public.",
    /* ─── Centre de notifications (3.13) ─── */
    notifsTitre: "Ce que Lehno signale",
    notifsToutLu: "Tout marquer comme lu",
    notifsAujourdhui: "Aujourd'hui",
    notifsAvant: "Avant",
    notifsVideTitre: "Rien à signaler",
    notifsVideTexte: "Les rappels et les contributions reçues apparaîtront ici.",
    notifRappel: (qui, j) => "Dans " + j + " jours : " + qui,
    notifAujourdhui: (qui) => "C'est aujourd'hui : " + qui,
    notifContribution: (n) => n === 1
      ? "Une contribution attend votre relecture"
      : n + " contributions attendent votre relecture",
    notifCredits: (n) => "Vous avez " + n + " crédits de plus",
    notifPortrait: (qui) => qui + " : le portrait est prêt",

    /* ─── À valider (3.8) ─── */
    validerIntro: "Rien de ce qui vient de l'extérieur n'entre dans vos fiches sans votre accord.",
    validerRetenir: "Retenir",
    validerEcarter: "Écarter",
    validerVideTitre: "Tout est traité",
    validerVideTexte: "Ce que vos proches déposeront passera ici avant d'entrer dans leurs fiches.",
    validerPour: (qui) => "Pour " + qui,
    validerSouhait: "Souhait",
    validerGout: "Goût",
    validerVoeu: "Mot reçu",
    validerRetenu: (n) => n === 1 ? "Une contribution retenue." : n + " contributions retenues.",
    validerEcarte: "Contribution écartée.",


    /* ─── Composition du portrait (3.7) ─── */
    compoTitre: "Sur quoi s'appuyer",
    compoMots: "Ce que vos notes disent",
    compoPlage: "Quelles notes retenir",
    compoPlageTout: "Tout l'historique",
    compoPlageAn: "Les douze derniers mois",
    compoPlageOccasion: "Une occasion",
    compoPlageAide: (n) => n + " notes retenues",
    compoTon: "Le ton",
    compoTonAide: "Repris du registre de la fiche.",
    compoLongueur: "La longueur",
    compoCourt: "Court", compoMoyen: "Moyen", compoLong: "Long",
    compoLancer: "Composer le portrait",

    /* ─── L'image du portrait (3.22) ─── */
    studioTitre: "Ce que vous voulez dire",
    studioOrientation: "L'orientation",
    orRelation: "Notre relation", orTesProgres: "Tes progrès", orNosProgres: "Nos progrès",
    orMotivation: "Une motivation", orSoutien: "Un soutien", orCaractere: "Ce qui te caractérise",
    orFierte: "Ma fierté", orAffection: "Mon affection", orGratitude: "Ma gratitude",
    orAppris: "Ce que tu m'as appris", orVoeu: "Un vœu", orHommage: "Un hommage",
    studioImage: "L'image",
    voieIllustration: "Une illustration", voiePhoto: "Une photo traitée", voieAucune: "Aucune",
    studioFamille: "La famille",
    famNature: "Nature", famAnimal: "Animal", famAbstrait: "Abstrait",
    famNatureAide: "Un paysage, une fleur, un élément.",
    famAnimalAide: "Un animal qui figure dans vos notes, ou qui lui correspond.",
    famAbstraitAide: "Des formes, un mouvement, une lumière.",
    studioLibre: "Ce qu'il faut savoir de lui pour le dessiner",
    studioLibrePlaceholder: "ex. ne se sépare jamais de son chat",
    studioLibreAide: "Complète vos notes. Non conservé au-delà.",
    studioStyle: "Le style",
    stylLumiere: "La lumière", stylSerigraphie: "La sérigraphie", stylSilhouette: "La silhouette",
    stylLumiereAide: "Le visage émerge d'un fond d'encre.",
    stylSerigraphieAide: "Quatre aplats, aucune nuance.",
    stylSilhouetteAide: "Le contour seul, sans traits.",
    studioPhotoAvis: "L'image est transmise à un service qui la transforme. Elle n'est pas conservée.",
    studioNote: "Votre note",
    studioNoteDefaut: "Fait avec soin par Valentine",
    studioAmbiance: "L'ambiance",
    studioLancer: "Composer le portrait",
    hommageAvis: "Un hommage se compose autrement : registre sobre, palette froide, aucun élément vif.",
    portraitNote: "Fait avec soin par Valentine",
    portraitCourt: "Tu as tenu tout le monde debout, cette année encore.",
    portraitMessage: "Tu refais le monde à minuit et tu nous ramènes au concret le lendemain matin. Cette année encore, tu as tenu tout le monde debout — et tu ne t'en es même pas aperçu.",
    portraitSignature2: "Valentine",
    portraitVoie: "L'image",
    portraitVoieIllustration: "Une illustration",
    portraitVoiePhoto: "Une photo",
    portraitVoieAucune: "Aucune",
    portraitAmbiance: "L'ambiance",
    portraitPhrase: "« l'année où tu as tout osé »",
    portraitMots: ["musique", "générosité", "rires", "Dakar", "rando", "curieux de tout"],
    portraitPlage: (p) => "D'après " + p,
    portraitEnregistrer: "Enregistrer l'image",
    portraitSurMonMur: "Partager sur mon Mur",
    portraitPartagerDehors: "Partager",
    portraitRetirerDuMur: "Retirer de mon Mur",

    /* ─── Préparation et génération (3.7) ─── */
    prepPour: (qui) => "Pour " + qui,
    prepIntro: "Rien ne part sans vous.",
    prepPortraitTitre: "Un portrait",
    prepPortraitTexte: "Ce qu'il y a à retenir, écrit à partir de vos notes. À garder pour vous ou à partager.",
    prepIdeesTitre: "Des idées de cadeau",
    prepIdeesTexte: "Cinq pistes qui lui ressemblent, du gratuit au plus cher.",
    prepMessageTitre: "Un message",
    prepMessageTexte: "Un brouillon dans votre ton, à ajuster avant d'envoyer.",
    prepDeja: "Déjà préparé",
    prepRelancer: "Refaire",
    prepVoir: "Voir",
    prepSensible: "Pas d'idée de cadeau pour une date comme celle-ci. Un mot, si vous le souhaitez.",

    genAttenteTitre: "Lehno écrit",
    genAttenteTexte: "Une minute environ. Vous pouvez fermer : ce sera là à votre retour.",
    genAttenteQuitter: "Faire autre chose en attendant",
    genErreurTitre: "L'écriture n'a pas abouti",
    genErreurTexte: "Votre crédit n'a pas été prélevé.",
    genReessayer: "Réessayer",

    cadrageTitre: "Avant de chercher",
    cadrageBudget: "Un budget ? (facultatif)",
    cadrageBudgetAide: "Sans budget, les idées vont du gratuit au plus cher.",
    cadrageNote: "Autre chose à savoir ? (facultatif)",
    cadrageNotePlaceholder: "ex. c'est un cadeau commun avec Célarine",
    cadrageLancer: "Chercher des idées",
    ideeRetenir: "Retenir",
    ideeLacher: "Retenue",
    ideeMarquerOfferte: "C'est ce que j'ai offert",
    ideeOfferte: "Offerte",
    ideeRetenueFait: (qui) => "Rangée dans les notes sur " + qui + ".",
    ideeOfferteFait: "Notée comme offerte.",
    ideeChoisir: "Choisir",
    ideeChoisie: "Choisie",
    resEnvoyerVia: "Envoyer via…",
    resCopierTexte: "Copier le texte",
    resCopie: "Texte copié.",
    noteOccasionDurable: "Aucune — la note décrit le proche",
    noteOccasionNouvelle: "Créer une date",
    noteDateQuoi: "Ce qu'on célèbre", noteDateQuand: "Quand",
    noteDatePoser: "Poser la date", noteDateGarder: "Annuler",
    noteOccasionAucune: "Aucune date enregistrée pour Valery.",
    resMessageTitre: "Votre message",
    resIdeesTitre: "Cinq idées",
    resAjuster: "Ajuster le texte",
    resEnvoyer: "Envoyer",
    resRegenerer: "Refaire",
    resJeter: "Jeter",
    resAjusteFini: "Garder ce texte", resAjusteAnnuler: "Revenir au texte écrit",
    envoiFait: (qui) => "Message marqué comme envoyé à " + qui + ".",
    envoiRappel: "Vous pourrez revenir dessus depuis la fiche.",


    connexionTitre: "Soyez là le jour J",
    connexionTexte: "Les dates de vos proches, et ce que vous savez d'eux. Le moment venu, vous avez déjà tout pour bien faire.",
    connexionErreur: "On n'a pas pu joindre Google. Les autres voies restent ouvertes.",
    avecGoogle: "Continuer avec Google",
    avecApple: "Continuer avec Apple",
    ou: "ou",
    champEmail: "Votre adresse e-mail",
    champEmailEx: "vous@exemple.fr",
    recevoirCode: "Recevoir un code",
    connexionPiedAvant: "En continuant, vous acceptez les ",
    connexionPiedCgu: "conditions d'utilisation",
    connexionPiedEntre: " et la ",
    connexionPiedConf: "politique de confidentialité",
    connexionPiedApres: ".",

    codeTitre: "Votre code est parti",
    codeTexte: "Regardez votre boîte de réception.",
    codeErreur: "Ce code ne correspond pas. Il vous reste deux essais.",
    codeValidite: (duree) => "Encore " + duree + " pour le saisir.",
    codeExpire: "Ce code a expiré.",
    codeRenvoiAttente: (s) => "Nouveau code possible dans " + s + " s",
    valider: "Valider",
    renvoyerCode: "Renvoyer un code",
    retour: "Retour",
    effacer: "Effacer",

    codeConnu: "Ce compte existe déjà : le pseudo est gardé.",
    pseudoTitre: "Choisissez votre pseudo",
    champPseudo: "Pseudo",
    pseudoAdresse: "lehno.app/valentine",
    pseudoPris: "Ce pseudo est pris. « valentine2 » est libre.",
    champParrain: "Code de parrainage (facultatif)",
    parrainValide: "Code valide",
    parrainInvalide: "Code invalide",
    continuer: "Continuer",

    bienvenueTitre: (prenom) => "Bienvenue, " + prenom,
    bienvenueTexte: "Votre carnet est ouvert. De quoi préparer vos premières célébrations : un portrait, des idées de cadeau, un mot juste.",
    bienvenueCadeau: "Cadeau de bienvenue",
    bienvenueParrainage: "Bonus de parrainage",
    bienvenueCredits: (n) => n + (n === 1 ? " crédit" : " crédits"),
    inviterAmi: "Inviter un ami",
    commencer: "Commencer",

    /* ─── Note (3.5) ─── */
    noteLabel: "Ce que vous voulez retenir",
    noteRange: "Rangé dans",
    noteSecondeCat: "Ajouter une catégorie",
    noteDeuxMax: "Deux catégories au plus.",
    noteRangement: "Rangement",
    notePourQui: "Pour qui",
    noteAjouterProche: "Ajouter",
    noteSansProche: "Désignez au moins un proche pour enregistrer.",
    noteOccasion: "À quelle occasion",
    noteOccasionAide: "Sans occasion, la note décrit le proche et vaut d'une année sur l'autre.",
    noteAjouter: "Ajouter",
    enregistrer: "Enregistrer",

    /* ─── Événement (3.6) ─── */
    evtType: "Type",
    evtAutreType: "Un autre type d'événement",
    evtPourQui: "Pour qui",
    evtDate: "La date",
    evtJour: "Jour", evtMois: "Mois", evtAnnee: "Année",
    evtDansJours: (n) => n === 0 ? "aujourd'hui" : n === 1 ? "demain" : "dans " + n + " jours",
    evtDetails: "Détails",
    evtNature: "Nature",
    evtNatureJoyeux: "Joyeux",
    evtNatureAide: "Une date sensible se détecte, et reste corrigeable.",
    evtRappel: "Rappel",
    evtRappelDefaut: "Une semaine avant",
    evtRappelChoix: ["Le jour même", "La veille", "Trois jours avant", "Une semaine avant", "Deux semaines avant", "Un mois avant"],
    evtDejaAnniv: "Valery a déjà un anniversaire au 24 août. Vous modifiez celui-là.",
    sensibleForm: "Une date comme celle-ci se prépare autrement : Lehno n'y proposera pas d'idée de cadeau.",

    /* ─── Recherche (3.15) ─── */
    videRechercheTitre: "Rien sous ce nom",
    videRechercheTexte: "Essayez un prénom, ou ajoutez cette personne.",
    ajouterCeProche: "Ajouter ce proche",

    /* ─── Souhait (3.19) ─── */
    souhaitExemple: "Un moulin à café manuel",
    souhaitAutre: "Un vinyle de Manu Dibango",
    souhaitPrix: "12 000 F",
    souhaitDisponible: "Disponible",
    souhaitReserve: "Réservé",
    souhaitLien: "Où le trouver",
    souhaitLienTexte: "torrefacteur-bonapriso.cm",
    souhaitOffertEtat: "Déjà offert",
    souhaitReservePar: (qui) => "Réservé par " + qui,
    souhaitReserveAnonyme: "Réservé — la personne n'a pas souhaité se faire connaître.",
    souhaitPhotoAjouter: "Ajouter une photo",
    souhaitPhotoRemplacer: "Remplacer la photo",
    souhaitRetirer: "Retirer ce souhait",
    souhaitRetraitTitre: "Retirer ce souhait ?",
    souhaitRetraitTexte: "Il quitte votre wishlist et les pages où vous l'avez partagée.",
    souhaitRetraitReserve: "Quelqu'un l'a réservé : la réservation part avec le souhait.",
    souhaitRetraitConfirmer: "Retirer",
    souhaitRetraitGarder: "Garder",
    souhaitRetireFait: "Le souhait est retiré.",
    souhaitRetourListe: "Revenir à la wishlist",
    souhaitEtat: "L'état",
    souhaitCandidatEtat: "Où en est cette idée",
    souhaitAEtudier: "À étudier",
    souhaitRetenu: "Retenu",
    souhaitEcarte: "Écarté",
    souhaitPrive: "Cette idée reste entre vous et Lehno.",
    souhaitRetirerCandidat: "Retirer l'idée",
    souhaitVisibleAide: "Les personnes qui ont le lien le verront.",
    souhaitPrecisions: "Précisions",
    souhaitPrecisionsTexte: "Le précédent rend l'âme. Un modèle repéré chez le torréfacteur de Bonapriso.",
    souhaitProvenance: "D'où ça vient",
    souhaitParole: "Valery a parlé d'un moulin à café manuel — le précédent rend l'âme.",
    souhaitOrigine: "noté",
    souhaitOrigineDate: "en mars",
    souhaitReserveTexte: "Célarine s'est fait connaître en le réservant.",
    souhaitVisible: "Visible sur la liste",
    souhaitOffert: "Marquer déjà offert",
    souhaitAjouter: "Ajouter",
    souhaitAjouterTitre: "Nouveau souhait",
    souhaitQuoi: "Ce que c'est",
    souhaitQuoiExemple: "ex. un moulin à café manuel",
    souhaitCombien: "Combien, à peu près",
    souhaitPrecisionsExemple: "ex. le précédent rend l'âme, plutôt en métal",
    modifier: "Modifier",
    videSouhaitsTitre: "Rien de listé pour l'instant",
    videSouhaitsTexte: "Ajoutez une idée, ou partagez un lien de collecte pour la faire remplir.",

    /* ─── Occasion (3.21) ─── */
    occPassee: "Passée",
    occSouhaits: "Wishlist",
    occSouhaitsTout: (n) => "Toute la wishlist · " + n,
    listeDe: (qui) => "Pour " + qui,
    listeRetenu: "Retenu",
    listeChercher: "Chercher des idées",
    occSansSouhait: "Cette date se prépare sans cadeau.",
    occNotes: "Notes pour cette occasion",
    occNoteTexte: "Prévoir de passer avant midi — l'après-midi, c'est le travail.",
    occNoteDate: "hier",
    occPreparer: "Préparer",
    occIdees: "Trouver des idées",
    occMessage: "Écrire le message",
    occMessagePret: "Message prêt",
    prepVoirIdees: "Revoir les idées",
    occMessageEnvoye: "Message envoyé",
    occMessageTexte: "Valery, 36 ans et toujours cette manie de refaire le monde à minuit.",
    occEnvoyeLe: "envoyé le",
    occVoeuxRecus: "Vœux reçus",
    occAucunVoeu: "Aucun mot pour cette occasion.",
    sensibleApproche: "Le 14 mars approche.",

    /* ─── Maintenance (3.29) ─── */
    maintTitre: "Lehno revient",
    maintTexte: "Une mise à jour est en cours.",
    maintHeure: (h) => "De retour vers " + h + ".",
    maintHeureExemple: "14 h 30",
    maintReessayer: "Réessayer"
  },

  en: {
    langue: "en",


    salut: (prenom) => "Hi " + prenom,
    etatRien: "Nothing in the coming weeks.",
    etatUnAujourdhui: "One date today.",
    etatUnSemaine: "One date this week.",
    etatDeuxSemaine: "Two dates this week.",
    etatPlusieursSemaine: (n) => n + " dates this week.",
    etatUnAujourdhuiEtSemaine: (n) => n === 1
      ? "One date today, another this week."
      : "One date today, " + n + " more this week.",
    etatLointain: (date) => "Nothing until " + date + ".",

    ceQuiApproche: "Coming up",
    plusTard: "Later",
    preparer: "Prepare",
    marquerEnvoye: "Mark as sent",
    laisserNote: "Write a note",
    ajouterAnniversaire: "Add a birthday",
    voirTout: "See all",
    moisPrecedent: "Previous month",
    moisSuivant: "Next month",
    voirPlus: "See more",
    prochesReste: (n) => "See more · " + n + " left",
    prochesCompte: (n) => n + " people",
    ficheSousTitre: "Birthday · 24 Aug · friendly",

    decompteBarre: (n) => n + (n === 1 ? " day" : " days"),
    decomptePhrase: (n) => n === 1 ? "in 1 day" : "in " + n + " days",

    accueilFaireListe: "Make my wishlist",
    accueilFaireListeSous: "The people close to you will know what to give.",

    videCarnetTitre: "Your notebook is ready",
    videCarnetTexte: "Add someone and their date. Lehno takes care of reminding you.",
    videRienTitre: "Nothing in the coming weeks",
    videRienTexte: "A good moment to note an idea while it's fresh.",

    prochesTitre: "Your people",
    rechercher: "Search for someone",
    triDate: "By date", triDateProche: "soonest first", triDateLoin: "furthest first",
    triAlphaAZ: "A–Z", triAlphaZA: "Z–A", triAlpha: "A → Z",
    ajouterProche: "Add someone",
    completer: "Fill in",
    videAnnuaireTitre: "No one in the notebook yet",
    videAnnuaireTexte: "Add someone and their date. The rest fills up over the year.",

    typeAnniversaire: "Birthday", typeMariage: "Wedding", typeRetraite: "Retirement",
    typeNaissance: "Birth", typeEtape: "Milestone", typeFete: "Celebration", typeAutre: "Other",
    aujourdhui: "today",


    horsConnexion: "Offline. Your notes and dates are still there to read.",
    horsConnexionFile: (n) => n === 1
      ? "Offline. One action will go out when the network is back."
      : "Offline. " + n + " actions will go out when the network is back.",
    chargement: "Loading",

    ongletAccueil: "Home", ongletDates: "Dates", ongletProches: "People",
    ongletMoi: "Me", ongletReglages: "Settings",






    feuilleCout: "What this costs",
    feuilleLancer: "Start",
    feuilleRecharger: "Top up",
    feuillePasMaintenant: "Not now",
    creditUnite: (n) => n + (n === 1 ? " credit" : " credits"),
    creditReste: (n) => n + (n === 1 ? " credit" : " credits") + " left",
    creditDepense: (n) => n + (n === 1 ? " credit" : " credits") + " spent",
    creditMot: (n) => n === 1 ? "credit" : "credits",

    murPrivAdresse: "lehno.app/valentine",
    murPrivPublie: "Published",
    murPrivPrive: "Offline",
    murPrivBascule: "Make my Wall public",
    murPrivExpose: "What's on show",
    murPrivGouts: "My tastes",
    murPrivDate: "My birthday",
    murPrivSouhaits: "My wishlist",
    murPrivMots: "Notes received",
    murPrivMotsCompte: (n) => n === 1 ? "1 note received" : n + " notes received",
    murPrivVoir: "See my page",
    murPrivApercu: "Preview my page",
    murPrivCopier: "Copy the link",
    murPrivCopie: "Link copied",
    murPrivEpingler: "Pin",
    murPrivEpingle: "Pinned",
    murPrivDetacher: "Unpin",
    murPrivEpinglesAide: "A pinned note shows on your Wall. The others don't leave this screen.",
    murPrivMotsListe: [
      { texte: "Thirty-four and still the first one dancing. Don't change a thing.", auteur: "Célarine", quand: "two days ago" },
      { texte: "Happy birthday — another year of keeping everyone standing.", auteur: "Awa", quand: "two days ago" },
      { texte: "Thank you for last year. You know why.", auteur: null, quand: "three days ago" }
    ],
    murPrivSansNom: "No name",
    murPrivRienExpose: "Choose what the people around you will see.",
    murPrivAucunMotTitre: "Nobody has written yet",
    murPrivAucunMotTexte: "Notes left by the people around you will show up here.",

    profilPhoto: "Change photo",
    champPrenom: "First name",
    profilNaissance: "My birthday",
    profilNaissanceAide: "It shows on my Wall if I put it there.",
    profilGouts: "My tastes and interests",
    profilGoutsAide: "One word, a comma, the next.",
    profilGoutsExemple: "jazz, ceramics, hiking",
    champLangue: "Interface language",
    profilLangueAide: "It changes right away.",

    reglagesQuand: "When to tell you",
    reglagesJ7: "A week before",
    reglagesJ1: "The day before",
    reglagesJour: "On the day",
    reglagesComment: "How",
    reglagesPush: "Notification",
    reglagesEmail: "Email",
    reglagesRefus: "Notifications are turned off at the phone level. Reminders go out by email.",
    reglagesActiver: "Turn them on in phone settings",
    reglagesHeure: "Sending time",
    reglagesHeures: ["7 am", "12 pm", "6 pm", "9 pm"],
    reglagesAutres: "Everything else",
    reglagesRecap: "The recap",
    reglagesRecapFreq: ["Every Monday", "The 1st of the month"],
    reglagesValider: "Contributions waiting for you",
    reglagesRelances: "A date is coming and nothing is ready",
    reglagesVieCompte: "A movement on your credits",
    reglagesSecuriteToujours: "Security alerts reach you whatever happens.",
    reglagesMuet: "No channel is open: nothing will reach you.",

    securiteMoyens: "How you sign in",
    securiteAppareils: "Signed-in devices",
    securiteCetAppareil: "This device",
    securiteDeconnecterTout: "Sign out other devices",
    securiteSupprimer: "Delete my account",
    securiteSupprimerAide: "Your pages, your notes and your Wall go with it.",
    securiteInhabituelle: "An unusual sign-in was detected on 12 August.",

    paiementAucuneTitre: "No method saved",
    paiementAucuneTexte: "One will save itself on your first purchase.",
    paiementAjouter: "Add a method",
    paiementExpire: "Expired",
    paiementDefaut: "Default",
    paiementAjoutTitre: "One more method",
    paiementNumero: "Mobile money number",
    paiementCarteNum: "Card number",
    paiementCarteExp: "Expires",
    paiementParDefaut: "Make it my default",
    paiementAjoutFait: "Method saved.",

    aideQuestions: "Common questions",
    aideContact: "Write to us",
    aideNoter: "Rate the app",
    aideVersion: "Version",

    reservIntro: "The gifts you reserved on other people's Walls.",
    reservVideTitre: "No reservations",
    reservVideTexte: "Anything you reserve on a Wall will show up here.",
    reservRetire: "Taken down by its owner",
    reservLiberer: "Release",

    moiCreditsSection: "Credits",
    moiPresence: "My public presence",
    moiCompte: "My account",
    moiAide: "Help",
    moiSolde: "Your balance",
    moiRecharger: "Top up",
    moiMonMur: "My Wall",
    moiMurVisible: "Visible to anyone with the link",
    moiMurDesactive: "Nothing is public yet",
    moiReservations: "My reservations",
    moiProfil: "My profile",
    moiSecurite: "Security and sessions",
    moiPaiement: "Payment methods",
    moiReglages: "Reminders and notifications",
    moiLangue: "Language",
    moiAideCentre: "Questions and contact",
    moiDeconnexion: "Sign out",

    moiSous: "What you show of yourself.",
    moiPartager: "Share",
    moiListes: "My wishlists",
    moiListesAucune: "No wishlist yet",
    moiListesUne: "1 wishlist",
    moiListesN: (n) => n + " wishlists",
    moiLienVoeux: "My wishes link",
    moiLienVoeuxOuvert: "Until 3 Sept.",
    moiLienVoeuxFerme: "Closed",
    moiMotsRecus: "Words received",
    moiMotsAucun: "No words",
    moiMotsN: (n) => n + " words",
    moiCreerListe: "Create a list",
    listeApercu: "View and share",
    pubListeTitre: (qui) => qui + "'s wishlist",
    pubListeQuand: (date) => "For " + date,
    pubListeReserver: "Reserve",
    pubListeReserve: "Reserved",
    pubListeDiscret: (qui) => qui + " can't see who reserves what.",
    pubListeSansCompte: "Reserving needs no account.",
    pubReserveFait: "Reserved, and it stays quiet.",
    portraitApprouveFait: "Portrait approved.",
    portraitJeteFait: "Portrait discarded.",
    portraitEnregistreFait: "Image saved.",
    collecteReactiveFait: "Link reactivated.",
    collecteMot: (qui) => "A word for " + qui,
    collecteMotAide: "It shows at the top of the page they open.",
    collecteMotExemple: "e.g. tell me what you'd love, I'll take care of the rest",
    collecteApercu: "See the page before sending",
    collecteRevoqueFait: "Link revoked.",
    lienCopieFait: "Link copied.",
    murVoirDehors: "The page opens in the browser.",
    reservLibereFait: "Reservation released.",
    securiteDeconnecteFait: "Other devices signed out.",
    securiteSupprimeDemande: "An email confirms the deletion.",
    rappelsActivesFait: "Notifications on.",
    photoMiseAJour: "Photo updated.",
    souhaitModifieFait: "Wish saved.",
    ficheSupprimeeFait: "Page deleted.",
    lienOuvreDehors: "The link opens in the browser.",
    pubListeInvite: "Keep one of my own",
    listeCreer: "New wishlist",
    listeSansDate: "No date",
    videListesTitre: "No wishlist yet",
    videListesTexte: "Open one to gather what you'd love.",
    listeNouvNom: "The name of the list",
    listeNouvNomExemple: "e.g. my birthday, the housewarming",
    listeNouvOccasion: "The occasion",
    listeNouvSansOccasion: "No occasion",
    listeNouvSansOccasionAide: "It carries over from year to year.",
    listeNouvDate: "Pick one of my dates",
    listeNouvCloture: "Close the list after the date",
    listeNouvFait: "Wishlist created.",
    souhaitModifierTitre: "Edit the wish",
    souhaitModifieEnregistre: "Wish updated.",
    murPrivOngletPage: "My page",
    murPrivOngletMots: (n) => n === 0 ? "The words" : "The words · " + n,
    reservOffert: "Mark as given",
    reservOffertFait: "Marked as given.",
    reservDejaOffert: "Given",
    moiPublierMur: "Publish my Wall",
    moiVitrine: "What you share",
    moiRetour: "What comes back",

    reglagesTitre: "Settings",
    reglagesArgent: "Credits and payments",
    reglagesCompte: "My account",
    reglagesAlertes: "Reminders and data",
    reglagesAide: "Help",
    moiRappels: "Reminders and notifications",
    moiDonnees: "My data",
    moiDonneesValeur: "Export, delete",

    donneesExport: "Request a copy",
    donneesExportAide: "Your pages, notes, dates and wishes, in one file.",
    donneesExportFait: "Request received.",
    donneesExportDemande: "The file reaches you by email within 24 hours.",
    donneesCollecte: "What Lehno keeps",
    donneesCollecteTexte: "What you write, and the dates you set. Nothing else is read.",

    supprTitre: "Close my account",
    supprPas: (n) => n + " of 3",
    supprCeQuiPart: "What goes with it",
    supprListe: ["Your people and everything you noted about them",
      "Your dates and the reminders that go with them",
      "Your wishlists, your Wall and the notes you received",
      "The links you shared — they will stop answering"],
    supprCeQuiReste: "What others reserved stays with them.",
    supprSolde: (n) => n <= 1 ? "You have " + n + " credit left." : "You have " + n + " credits left.",
    supprSoldeRemboursable: "The balance goes back to the payment method on file.",
    supprSoldeVide: "There is no credit left to refund.",
    supprRaison: "What makes you leave",
    supprRaisonFacultatif: "Optional.",
    supprRaisons: ["I no longer need it", "Too expensive", "It didn't help me",
      "I'll come back later"],
    supprRaisonAutre: "Anything else?",
    supprConfirmer: "One last thing",
    supprPseudo: "Your handle",
    supprCode: "The code sent by SMS",
    supprCodeRenvoyer: "Send the code again",
    supprCodeRenvoye: "Code sent again.",
    supprSuivant: "Continue",
    supprFermer: "Close my account",
    supprRenoncer: "Never mind",
    supprFait: "Your account is closed.",
    supprRevenir: "Back to Lehno",
    supprGrace: "Thirty days to come back: write to bonjour@lehno.cm from this address. After that, everything is erased.",

    versementTitre: "The transfer",
    versementTexte: "Send the amount to this number, then upload the receipt.",
    versementCompte: "The Lehno account",
    versementNumero: "+237 6 91 00 00 00",
    versementCopier: "Copy the number",
    versementCopieFait: "Number copied.",
    versementRecu: "Upload my receipt",
    versementRecuFait: "Receipt received. The credit lands within 24 hours.",
    versementDelai: "The credit lands within 24 hours.",
    mouvementsTitre: "Movements",
    mouvementsAucun: "No movement yet.",
    evtTitreAnniv: "New birthday",
    cartNoter: "Note an idea",
    occNoterPour: (date) => "Note an idea for " + date,

    rechargeTitre: "How many credits?",
    rechargeIntro: "One credit per piece created for you.",
    rechargeUnite: (n) => n === 1 ? "1 credit" : n + " credits",
    rechargeEconomie: (p) => "−" + p + "%",
    rechargeAttenteEnCours: "Waiting",
    rechargeAttenteSecours: "If nothing shows up, dial your operator's code:",
    rechargeRecapTitre: "Before you pay",
    rechargeRecapCredits: "Credits",
    rechargeRecapMontant: "Amount",
    rechargeRecapFrais: (v) => "fee " + v,
    rechargeRecapTotal: "Total to pay",
    rechargeRecapModifier: "Change the pack",
    rechargeMoyen: "How to pay",
    rechargeMobile: "Mobile money",
    rechargeCarte: "Card",
    rechargePayer: (m) => "Pay " + m,
    rechargeAttenteTitre: "Confirm on your phone",
    rechargeAttenteTexte: "A request shows up on your phone. Allow one to two minutes.",
    rechargeAttenteExpire: "Without your approval, the request expires on its own.",
    rechargeAttenteFermer: "Close",
    rechargeAboutiTitre: "Credits added",
    rechargeAboutiTexte: (n) => n + " credits are on your account.",
    rechargeEchecTitre: "The payment didn't go through",
    rechargeEchecTexte: "Nothing was taken.",

    parrainageTitre: "Invite someone, you both gain",
    parrainageTexte: "Your code gives 2 credits to whoever signs up, and 2 credits to you.",
    parrainageCode: "VAL-4KX2",
    parrainagePartager: "Share my code",
    parrainageFilleuls: (n) => n === 1 ? "One person used your code" : n + " people used your code",
    parrainageAucun: "Nobody yet.",

    procheNotes: (n) => n === 1 ? "1 note" : n + " notes",
    procheAucuneNote: "Nothing noted yet",
    procheProchaine: (quoi, date) => quoi + " on " + date,
    ficheInterets: "Interests and tastes",
    ficheNotes: "What you've noted",
    categories: { gout: "Taste", idee: "Idea", nogo: "Avoid", souvenir: "Memory", aclasser: "Unfiled" },
    reclasserAria: (l) => "Change category — currently: " + l,
    noteTitreModifier: "Edit note",
    noteSupprimer: "Delete this note",
    noteIdee: "Idea",
    noteEviter: "Avoid",
    ficheIdees: "Gift ideas",
    ficheNogo: "What to avoid",
    ficheNogoTexte: "I don't drink alcohol.",
    ficheIdeeTexte: "Valery mentioned a hand coffee grinder — the old one is on its last legs.",
    fichePreparer: (date) => "Prepare for " + date,
    ficheAjouterNote: "Add a note",
    ficheAjouterDate: "Add a date",
    fichePortraits: "Their portraits",
    ficheCollecte: "Have the page filled in",
    ficheIdentite: "Edit details",
    ficheGoutsReste: (n) => "+" + n + " more",
    ficheCollecteCourt: "Get it filled", ficheIdentiteCourt: "Details", fichePortraitsCourt: "Portraits",
    datesTitre: "Your dates", ajouterDate: "Add a date", vueListe: "List", vueCalendrier: "Calendar",
    joursCourts: ["M", "T", "W", "T", "F", "S", "S"],
    calendrierAout: "August 2026", calendrierRien: "Nothing that day.",
    moisAout: "August", moisSept: "September",
    moisCourant: "This month",
    videDatesTitre: "No dates yet",
    videDatesTexte: "Add the first one: a birthday, a farewell, an anniversary.",

    collecteTitre: "Let Valery fill it in",
    collecteIntro: "Send this link: whatever comes back passes through your review before it enters the page.",
    collecteLien: "lehno.app/c/8Kd2p",
    collectePartager: "Share the link",
    collecteCopier: "Copy the link",
    collecteRevoquer: "Revoke the link",
    collecteReactiver: "Create a new link",
    collecteEtatActif: "Active",
    collecteEtatRevoque: "Revoked",
    collecteRecu: (n) => n === 1 ? "One reply received" : n + " replies received",
    collecteAucune: "No replies yet.",
    collecteRevoqueTexte: "This link leads nowhere now. You can create another one.",

    identiteTitre: "What Lehno needs to know",
    identiteIntro: "These few things shape what Lehno writes.",
    champAppelle: "What you call them",
    champAppelleAide: "This is the name that appears in messages — “Mum”, “mate”.",
    champRelation: "The relationship",
    relFamilleProche: "Close family", relFamilleEtendue: "Extended family",
    relAmi: "Friend", relPartenaire: "Partner", relCollegue: "Colleague",
    relPro: "Work contact", relConnaissance: "Acquaintance",
    champRelationHint: "Where you met",
    champRelationHintAide: "A sentence is enough: “we met at uni”.",
    registreFamilier: "Familiar", registreFormel: "Formal",
    champVille: "City", champVilleAide: "To suggest places and outings.",
    champCanal: "How you write to them",
    champCanalAide: "Shapes the length of the draft.",
    canalWhatsapp: "WhatsApp", canalSms: "SMS", canalEmail: "Email", canalAutre: "Other",
    evtLabel: "The label",
    evtLabelAide: "As you write it — it shows untranslated.",
    evtNatureSensible: "Sensitive",
    champNom: "Name",
    champLien: "How you're related",
    champRegistre: "Register",
    registreAmical: "Friendly",
    registreFamilial: "Family",
    registreRespectueux: "Respectful",
    registreComplice: "Close",
    identiteRegistreAide: "The tone of the drafts.",
    champLangueProche: "Language of messages",
    identiteSupprimer: "Delete this page",
    identiteSupprimerAide: "Its notes and dates go with it.",

    portraitAValider: "To approve",
    portraitApprouver: "Approve",
    portraitSignature: "Your note at the foot",
    portraitSignatureAide: "“Made with care by Valentine”, under the message. The logotype always stays.",
    portraitAucunTitre: "No portrait yet",
    portraitAucunTexte: "The first one will come from what you noted.",

    reprisesIntro: "Nothing gets lost. What you started is waiting here.",
    reprisesVideTitre: "All caught up",
    reprisesVideTexte: "Anything you start without finishing will wait for you here.",
    repriseBrouillon: "Message draft",
    repriseIdees: "Gift ideas",
    reprisePortrait: "Portrait",
    repriseDepassee: "The date has passed",
    repriseReprendre: "Pick up",

    pubRevoqueTexte: "Ask whoever sent it for a new link.",
    pubCollectePlaceholder: "e.g. their birthday is 22 March, and they love ceramics",
    murGoutsLabel: (qui) => "What " + qui + " likes",
    murSouhaitsLabel: "What would make them happy",
    murListeCta: "See their wishlist",
    murMotLabel: "Notes received",
    murMotExemple: (qui) => "Happy birthday " + qui + " — another year of keeping everyone standing.",
    murMotCta: "Leave a note",
    pubCollecteQui: (qui) => qui + " is planning something for you.",
    pubCollecteAvis: "What you leave here goes through their review before it enters their page.",
    pubCollecteDate: "Your date",
    pubCollecteDateAide: "The day and month are enough.",
    pubCollecteSouhaits: "What would make you happy",
    pubCollecteSouhaitsAide: "One idea per line. Nothing is required.",
    pubCollecteSouhaitsPlaceholder: "e.g. a hand coffee grinder",
    pubCollecteMot: "A word for Valentine",
    pubCollecteMotPlaceholder: "e.g. thank you for thinking of me",
    pubCollecteAjouter: "Add a wish",
    pubCollecteChamp: "What you'd like to tell them",
    pubCollecteAide: "Their date, what would make them happy, a note — whatever you like.",
    pubReconnu: (qui) => "You're signed in as " + qui + ".",
    pubSansCompte: "Replying needs no account.",
    pubMurSansCompte: "Leaving a note needs no account.",
    pubMurTitre: (qui) => qui + "'s Wall",
    pubCollecteTitre: "Valentine invites you to fill in what will help",
    pubVoeuTitre: (qui) => "Leave " + qui + " a note",
    pubVoeuChamp: "Your message",
    pubVoeuPlaceholder: "e.g. happy birthday — another year of keeping everyone standing",
    pubQui: "Your name (optional)",
    pubQuiAide: "Without a name, your note arrives anonymous.",
    pubEnvoyer: "Send",
    pubEnvoye: "Sent. Célarine will see it.",
    pubInviteTitre: "And your own dates?",
    pubInviteTexte: "Lehno remembers the dates that matter and what you know about the people you love.",
    pubInviteAction: "Create my space",
    pubInvitePlusTard: "Not now",
    pubRevoque: "This link is no longer valid.",
    pubVoeuxClos: "The window has closed. Célarine has already had their notes.",
    pubMurPrive: "Célarine hasn't made anything public.",
    notifsTitre: "What Lehno flags",
    notifsToutLu: "Mark all as read",
    notifsAujourdhui: "Today",
    notifsAvant: "Earlier",
    notifsVideTitre: "Nothing to flag",
    notifsVideTexte: "Reminders and incoming contributions will show up here.",
    notifRappel: (qui, j) => "In " + j + " days: " + qui,
    notifAujourdhui: (qui) => "Today: " + qui,
    notifContribution: (n) => n === 1
      ? "One contribution is waiting for your review"
      : n + " contributions are waiting for your review",
    notifCredits: (n) => n + " more credits on your account",
    notifPortrait: (qui) => qui + ": the portrait is ready",

    validerIntro: "Nothing from the outside enters your pages without your say.",
    validerRetenir: "Keep",
    validerEcarter: "Set aside",
    validerVideTitre: "All caught up",
    validerVideTexte: "What the people around you send will pass through here first.",
    validerPour: (qui) => "For " + qui,
    validerSouhait: "Wish",
    validerGout: "Taste",
    validerVoeu: "Note received",
    validerRetenu: (n) => n === 1 ? "One contribution kept." : n + " contributions kept.",
    validerEcarte: "Contribution set aside.",


    compoTitre: "What to draw on",
    compoMots: "What your notes say",
    compoPlage: "Which notes to use",
    compoPlageTout: "Everything",
    compoPlageAn: "The last twelve months",
    compoPlageOccasion: "One occasion",
    compoPlageAide: (n) => n + " notes used",
    compoTon: "The tone",
    compoTonAide: "Taken from the register on their page.",
    compoLongueur: "The length",
    compoCourt: "Short", compoMoyen: "Medium", compoLong: "Long",
    compoLancer: "Compose the portrait",

    studioTitre: "What you want to say",
    studioOrientation: "The direction",
    orRelation: "Our relationship", orTesProgres: "Your progress", orNosProgres: "Our progress",
    orMotivation: "Encouragement", orSoutien: "Support", orCaractere: "What makes you you",
    orFierte: "My pride", orAffection: "My affection", orGratitude: "My gratitude",
    orAppris: "What you taught me", orVoeu: "A wish", orHommage: "A tribute",
    studioImage: "The image",
    voieIllustration: "An illustration", voiePhoto: "A treated photo", voieAucune: "None",
    studioFamille: "The family",
    famNature: "Nature", famAnimal: "Animal", famAbstrait: "Abstract",
    famNatureAide: "A landscape, a flower, an element.",
    famAnimalAide: "An animal they love, or one that fits them.",
    famAbstraitAide: "Shapes, movement, light.",
    studioLibre: "What we should know to draw them",
    studioLibrePlaceholder: "e.g. never far from that cat",
    studioLibreAide: "Adds to your notes. Not kept afterwards.",
    studioStyle: "The style",
    stylLumiere: "Light", stylSerigraphie: "Screen print", stylSilhouette: "Silhouette",
    stylLumiereAide: "The face emerges from an ink ground.",
    stylSerigraphieAide: "Four flat tones, no gradient.",
    stylSilhouetteAide: "The outline alone, no features.",
    studioPhotoAvis: "The image is sent to a service that transforms it. It is not kept.",
    studioNote: "Your note",
    studioNoteDefaut: "Made with care by Valentine",
    studioAmbiance: "The mood",
    studioLancer: "Compose the portrait",
    hommageAvis: "A tribute is composed differently: sober register, cool palette, nothing vivid.",
    portraitNote: "Made with care by Valentine",
    portraitCourt: "You kept everyone standing, this year again.",
    portraitMessage: "You fix the world at midnight and bring us back to earth the next morning. This year again, you kept everyone standing — and never once noticed.",
    portraitSignature2: "Valentine",
    portraitVoie: "The image",
    portraitVoieIllustration: "An illustration",
    portraitVoiePhoto: "A photo",
    portraitVoieAucune: "None",
    portraitAmbiance: "The mood",
    portraitPhrase: "“the year you dared everything”",
    portraitMots: ["music", "generosity", "laughter", "Dakar", "hiking", "curious about everything"],
    portraitPlage: (p) => "From " + p,
    portraitEnregistrer: "Save the image",
    portraitSurMonMur: "Share on my Wall",
    portraitPartagerDehors: "Share",
    portraitRetirerDuMur: "Take it off my Wall",

    prepPour: (qui) => "For " + qui,
    prepIntro: "Nothing goes out without you.",
    prepPortraitTitre: "A portrait",
    prepPortraitTexte: "What's worth remembering, written from your notes. Keep it or share it.",
    prepIdeesTitre: "Gift ideas",
    prepIdeesTexte: "Five directions that look like them, from free to pricier.",
    prepMessageTitre: "A message",
    prepMessageTexte: "A draft in your voice, to adjust before sending.",
    prepDeja: "Already prepared",
    prepRelancer: "Redo",
    prepVoir: "See",
    prepSensible: "No gift ideas for a date like this one. A few words, if you want them.",

    genAttenteTitre: "Lehno is writing",
    genAttenteTexte: "About a minute. You can close this: it will be here when you come back.",
    genAttenteQuitter: "Do something else meanwhile",
    genErreurTitre: "The writing didn't go through",
    genErreurTexte: "Your credit wasn't taken.",
    genReessayer: "Try again",

    cadrageTitre: "Before we look",
    cadrageBudget: "A budget? (optional)",
    cadrageBudgetAide: "Without one, ideas range from free to expensive.",
    cadrageNote: "Anything else to know? (optional)",
    cadrageNotePlaceholder: "e.g. it's a joint gift with Célarine",
    cadrageLancer: "Look for ideas",
    ideeRetenir: "Keep",
    ideeLacher: "Kept",
    ideeMarquerOfferte: "This is what I gave",
    ideeOfferte: "Given",
    ideeRetenueFait: (qui) => "Filed with the notes on " + qui + ".",
    ideeOfferteFait: "Marked as given.",
    ideeChoisir: "Choose",
    ideeChoisie: "Chosen",
    resEnvoyerVia: "Send via…",
    resCopierTexte: "Copy the text",
    resCopie: "Text copied.",
    noteOccasionDurable: "None — the note describes the person",
    noteOccasionNouvelle: "Add a date",
    noteDateQuoi: "What it celebrates", noteDateQuand: "When",
    noteDatePoser: "Add the date", noteDateGarder: "Cancel",
    noteOccasionAucune: "No date saved for Valery yet.",
    resMessageTitre: "Your message",
    resIdeesTitre: "Five ideas",
    resAjuster: "Adjust the text",
    resEnvoyer: "Send",
    resRegenerer: "Redo",
    resJeter: "Discard",
    resAjusteFini: "Keep this text", resAjusteAnnuler: "Back to the written text",
    envoiFait: (qui) => "Message marked as sent to " + qui + ".",
    envoiRappel: "You can come back to it from their page.",


    connexionTitre: "Be there on the day",
    connexionTexte: "The dates of the people you love, and what you know about them. When the day comes, you already have what you need.",
    connexionErreur: "We couldn't reach Google. The other ways are still open.",
    avecGoogle: "Continue with Google",
    avecApple: "Continue with Apple",
    ou: "or",
    champEmail: "Your email address",
    champEmailEx: "you@example.com",
    recevoirCode: "Send me a code",
    connexionPiedAvant: "By continuing, you agree to the ",
    connexionPiedCgu: "terms of use",
    connexionPiedEntre: " and the ",
    connexionPiedConf: "privacy policy",
    connexionPiedApres: ".",

    codeTitre: "Your code is on its way",
    codeTexte: "Check your inbox.",
    codeErreur: "That code doesn't match. Two tries left.",
    codeValidite: (duree) => duree + " left to enter it.",
    codeExpire: "This code has expired.",
    codeRenvoiAttente: (s) => "New code in " + s + "s",
    valider: "Confirm",
    renvoyerCode: "Send another code",
    retour: "Back",
    effacer: "Clear",

    codeConnu: "This account already exists — the handle stays.",
    pseudoTitre: "Pick your handle",
    champPseudo: "Handle",
    pseudoAdresse: "lehno.app/valentine",
    pseudoPris: "That one's taken. \u201Cvalentine2\u201D is free.",
    champParrain: "Referral code (optional)",
    parrainValide: "Valid code",
    parrainInvalide: "Invalid code",
    continuer: "Continue",

    bienvenueTitre: (prenom) => "Welcome, " + prenom,
    bienvenueTexte: "Your notebook is open. Enough to prepare your first celebrations: a portrait, gift ideas, the right words.",
    bienvenueCadeau: "Welcome gift",
    bienvenueParrainage: "Referral bonus",
    bienvenueCredits: (n) => n + (n === 1 ? " credit" : " credits"),
    inviterAmi: "Invite a friend",
    commencer: "Get started",

    noteLabel: "What you want to remember",
    noteRange: "Filed under",
    noteSecondeCat: "Add a category",
    noteDeuxMax: "Two categories at most.",
    noteRangement: "Filing",
    notePourQui: "About whom",
    noteAjouterProche: "Add",
    noteSansProche: "Name at least one person to save this.",
    noteOccasion: "For which occasion",
    noteOccasionAide: "With no occasion, the note describes the person and keeps working year after year.",
    noteAjouter: "Add",
    enregistrer: "Save",

    evtType: "Type",
    evtAutreType: "Another kind of event",
    evtPourQui: "About whom",
    evtDate: "The date",
    evtJour: "Day", evtMois: "Month", evtAnnee: "Year",
    evtDansJours: (n) => n === 0 ? "today" : n === 1 ? "tomorrow" : "in " + n + " days",
    evtDetails: "Details",
    evtNature: "Nature",
    evtNatureJoyeux: "Joyful",
    evtNatureAide: "A sensitive date is detected, and stays editable.",
    evtRappel: "Reminder",
    evtRappelDefaut: "One week before",
    evtRappelChoix: ["On the day", "The day before", "Three days before", "One week before", "Two weeks before", "One month before"],
    evtDejaAnniv: "Valery already has a birthday on 24 Aug. You're editing that one.",
    sensibleForm: "A date like this one is prepared differently: Lehno won't suggest gift ideas for it.",

    videRechercheTitre: "Nothing under that name",
    videRechercheTexte: "Try a first name, or add this person.",
    ajouterCeProche: "Add this person",

    souhaitExemple: "A hand coffee grinder",
    souhaitAutre: "A Manu Dibango record",
    souhaitPrix: "12,000 F",
    souhaitDisponible: "Available",
    souhaitReserve: "Reserved",
    souhaitLien: "Where to find it",
    souhaitLienTexte: "torrefacteur-bonapriso.cm",
    souhaitOffertEtat: "Already given",
    souhaitReservePar: (qui) => "Reserved by " + qui,
    souhaitReserveAnonyme: "Reserved — they chose not to say who.",
    souhaitPhotoAjouter: "Add a photo",
    souhaitPhotoRemplacer: "Replace the photo",
    souhaitRetirer: "Remove this wish",
    souhaitRetraitTitre: "Remove this wish?",
    souhaitRetraitTexte: "It leaves your wishlist and the pages where you shared it.",
    souhaitRetraitReserve: "Someone reserved it — the reservation goes with the wish.",
    souhaitRetraitConfirmer: "Remove",
    souhaitRetraitGarder: "Keep",
    souhaitRetireFait: "The wish is removed.",
    souhaitRetourListe: "Back to the wishlist",
    souhaitEtat: "The state",
    souhaitCandidatEtat: "Where this idea stands",
    souhaitAEtudier: "To consider",
    souhaitRetenu: "Kept",
    souhaitEcarte: "Set aside",
    souhaitPrive: "This idea stays between you and Lehno.",
    souhaitRetirerCandidat: "Remove the idea",
    souhaitVisibleAide: "Anyone with the link will see it.",
    souhaitPrecisions: "Details",
    souhaitPrecisionsTexte: "The old one is on its last legs. A model spotted at the roaster in Bonapriso.",
    souhaitProvenance: "Where this came from",
    souhaitParole: "Valery mentioned a hand coffee grinder — the old one is on its last legs.",
    souhaitOrigine: "noted",
    souhaitOrigineDate: "in March",
    souhaitReserveTexte: "Célarine let you know they reserved it.",
    souhaitVisible: "Shown on the list",
    souhaitOffert: "Mark as already given",
    souhaitAjouter: "Add",
    souhaitAjouterTitre: "New wish",
    souhaitQuoi: "What it is",
    souhaitQuoiExemple: "e.g. a hand coffee grinder",
    souhaitCombien: "Roughly how much",
    souhaitPrecisionsExemple: "e.g. the old one is failing, metal if possible",
    modifier: "Edit",
    videSouhaitsTitre: "Nothing listed yet",
    videSouhaitsTexte: "Add an idea, or share a link and let it be filled in.",

    occPassee: "Past",
    occSouhaits: "Wishlist",
    occSouhaitsTout: (n) => "The whole wishlist · " + n,
    listeDe: (qui) => "For " + qui,
    listeRetenu: "Kept",
    listeChercher: "Look for ideas",
    occSansSouhait: "This date is prepared without a gift.",
    occNotes: "Notes for this occasion",
    occNoteTexte: "Go before noon — he works in the afternoon.",
    occNoteDate: "yesterday",
    occPreparer: "Prepare",
    occIdees: "Find some ideas",
    occMessage: "Write the message",
    occMessagePret: "Message ready",
    prepVoirIdees: "See the ideas again",
    occMessageEnvoye: "Message sent",
    occMessageTexte: "Valery, 36 and still that habit of fixing the world at midnight.",
    occEnvoyeLe: "sent on",
    occVoeuxRecus: "Wishes received",
    occAucunVoeu: "No words for this occasion.",
    sensibleApproche: "14 March is coming up.",

    maintTitre: "Lehno will be right back",
    maintTexte: "An update is under way.",
    maintHeure: (h) => "Back around " + h + ".",
    maintHeureExemple: "2:30 pm",
    maintReessayer: "Try again"
  }
};

/* Mes wishlists : ce que je demande, rangé par occasion. La même donnée sert
   l'écran du propriétaire et l'aperçu visiteur — sans quoi les deux côtés
   comptaient des souhaits différents. */
export const MES_LISTES = {
  fr: [
    { id: "anniv", nom: "Mon anniversaire", quand: "3 septembre", souhaits: [
      { id: "s1", quoi: "Un moulin à café manuel", prix: "12 000 F", etat: "reserve",
        precisions: "Le mien rend l'âme. Un modèle repéré chez le torréfacteur de Bonapriso.",
        lien: "torrefacteur-bonapriso.cm", reservePar: "Célarine" },
      { id: "s2", quoi: "Un vinyle de Manu Dibango", prix: "8 000 F",
        precisions: "N'importe quel pressage d'origine ferait l'affaire.",
        lien: "disquaire-akwa.cm" },
      { id: "s3", quoi: "Un cours de céramique", prix: "25 000 F",
        precisions: "L'atelier de Bonanjo, le samedi matin." }
    ]},
    { id: "libre", nom: "Sans occasion", souhaits: [
      { id: "s4", quoi: "Des gants de jardin", prix: "4 000 F", precisions: "Taille 7." },
      { id: "s5", quoi: "Une lampe de lecture", prix: "15 000 F", etat: "offert",
        precisions: "À pince, pour la tête de lit.", reservePar: "Valery Bah" }
    ]}
  ],
  en: [
    { id: "anniv", nom: "My birthday", quand: "3 September", souhaits: [
      { id: "s1", quoi: "A hand coffee grinder", prix: "12,000 F", etat: "reserve",
        precisions: "Mine is on its last legs. A model spotted at the roaster in Bonapriso.",
        lien: "torrefacteur-bonapriso.cm", reservePar: "Célarine" },
      { id: "s2", quoi: "A Manu Dibango record", prix: "8,000 F",
        precisions: "Any original pressing would do.", lien: "disquaire-akwa.cm" },
      { id: "s3", quoi: "A ceramics class", prix: "25,000 F",
        precisions: "The Bonanjo studio, Saturday mornings." }
    ]},
    { id: "libre", nom: "No occasion", souhaits: [
      { id: "s4", quoi: "Garden gloves", prix: "4,000 F", precisions: "Size 7." },
      { id: "s5", quoi: "A reading lamp", prix: "15,000 F", etat: "offert",
        precisions: "A clip-on, for the headboard.", reservePar: "Valery Bah" }
    ]}
  ]
};


/* Les mouvements du solde : ce qui est entré, ce qui est sorti. Au lancement,
   c'est tout ce que l'écran des crédits a à montrer avec le solde. */
export const MOUVEMENTS = {
  fr: [
    { id: "m1", quoi: "Versement reçu", quand: "12 août", delta: 12 },
    { id: "m2", quoi: "Message pour Célarine", quand: "9 août", delta: -1 },
    { id: "m3", quoi: "Idées pour Valery", quand: "2 août", delta: -1 },
    { id: "m4", quoi: "Bienvenue", quand: "28 juillet", delta: 3 }
  ],
  en: [
    { id: "m1", quoi: "Payment received", quand: "12 Aug", delta: 12 },
    { id: "m2", quoi: "Message for Célarine", quand: "9 Aug", delta: -1 },
    { id: "m3", quoi: "Ideas for Valery", quand: "2 Aug", delta: -1 },
    { id: "m4", quoi: "Welcome", quand: "28 July", delta: 3 }
  ]
};

export const MES_DATES = {
  fr: [
    { id: "anniv", quoi: "Mon anniversaire", quand: "3 septembre" },
    { id: "cremaillere", quoi: "La crémaillère", quand: "12 octobre" }
  ],
  en: [
    { id: "anniv", quoi: "My birthday", quand: "3 September" },
    { id: "cremaillere", quoi: "The housewarming", quand: "12 October" }
  ]
};

/* Ce qu'on peut offrir à un proche : la même liste sur l'occasion et sur la
   wishlist du proche, pour que le compte annoncé soit le compte affiché. */
export const SOUHAITS_PROCHE = {
  fr: [
    { id: "c1", quoi: "Un moulin à café manuel", prix: "12 000 F", etat: "offert",
      precisions: "Offert l'an dernier — de quoi ne pas se répéter.",
      parole: "Valery a parlé d'un moulin à café manuel — le précédent rend l'âme.",
      origine: "noté", origineDate: "en mars", lien: "torrefacteur-bonapriso.cm" },
    { id: "c2", quoi: "Un vinyle de Manu Dibango", prix: "8 000 F", etat: "ecarte",
      precisions: "La platine est en panne depuis le déménagement.",
      lien: "disquaire-akwa.cm" },
    { id: "c3", quoi: "Un carnet relié à la main", prix: "6 000 F", etat: "retenu",
      precisions: "Écrit tous les matins, toujours sur des carnets bon marché.",
      origine: "noté", origineDate: "en juin",
      parole: "Valery a dit qu'écrire sur du beau papier changeait tout.",
      lien: "atelier-relieur-douala.cm" },
    { id: "c4", quoi: "Une paire de gants de jardin", prix: "4 000 F",
      precisions: "Le balcon s'est rempli cette année." },
    { id: "c5", quoi: "Un cours de céramique", prix: "25 000 F",
      precisions: "L'atelier de Bonanjo prend des débutants.",
      lien: "atelier-bonanjo.cm" }
  ],
  en: [
    { id: "c1", quoi: "A hand coffee grinder", prix: "12,000 F", etat: "offert",
      precisions: "Given last year — so as not to repeat it.",
      parole: "Valery mentioned a hand coffee grinder — the old one is giving up.",
      origine: "noted", origineDate: "in March", lien: "torrefacteur-bonapriso.cm" },
    { id: "c2", quoi: "A Manu Dibango record", prix: "8,000 F", etat: "ecarte",
      precisions: "The turntable has been broken since the move.",
      lien: "disquaire-akwa.cm" },
    { id: "c3", quoi: "A hand-bound notebook", prix: "6,000 F", etat: "retenu",
      precisions: "Writes every morning, always on cheap notebooks.",
      origine: "noted", origineDate: "in June",
      parole: "Valery said writing on good paper changed everything.",
      lien: "atelier-relieur-douala.cm" },
    { id: "c4", quoi: "A pair of garden gloves", prix: "4,000 F",
      precisions: "The balcony filled up this year." },
    { id: "c5", quoi: "A ceramics class", prix: "25,000 F",
      precisions: "The Bonanjo studio takes beginners.", lien: "atelier-bonanjo.cm" }
  ]
};

/* Les données d'exemple — les mêmes personnes partout, comme validé. */
export const PROCHES = [
  { id: "awa", nom: "Célarine", type: "anniversaire", date: "22 août", dateEn: "22 Aug",
    note: "Célarine a parlé d'un cours de céramique, tout près d'ici.",
    noteEn: "Célarine mentioned a ceramics class, right nearby.",
    noteOrigine: "noté", noteOrigineEn: "noted", noteDate: "en mars", noteDateEn: "in March",
    jours: 0, notes: 3 },
  { id: "valery", nom: "Valery Bah", type: "anniversaire", date: "24 août", dateEn: "24 Aug",
    note: "Valery a parlé d'un moulin à café manuel — le précédent rend l'âme.",
    noteEn: "Valery mentioned a hand coffee grinder — the old one is on its last legs.",
    noteOrigine: "noté", noteOrigineEn: "noted", noteDate: "en mars", noteDateEn: "in March",
    jours: 3, notes: 9 },
  { id: "kader", nom: "Kader Diop", type: "anniversaire", date: "28 août", dateEn: "28 Aug",
    precision: "30 ans", precisionEn: "turning 30",
    note: "Kader a dit n'avoir plus rien pour écrire debout.",
    noteEn: "Kader said there's nothing left to write with on the go.",
    noteOrigine: "noté", noteOrigineEn: "noted", noteDate: "en juin", noteDateEn: "in June",
    jours: 6, notes: 4 },
  { id: "mathias", nom: "Mathias & Rose", type: "mariage", date: "30 août", dateEn: "30 Aug",
    precision: "5 ans", precisionEn: "5 years", jours: 9, notes: 2 },
  { id: "maman", nom: "Maman", type: "retraite", date: "2 sept.", dateEn: "2 Sep",
    jours: 12, notes: 14 },
  { id: "nour", nom: "Nour & moi", nomEn: "Nour & me", type: "etape", date: "14 sept.", dateEn: "14 Sep",
    precision: "Six mois", precisionEn: "Six months", jours: 24, notes: 6 }
];

/* L'état « carnet fourni » de la liste des proches : la même donnée, en nombre.
   La date n'est pas écrite à la main — elle se déduit du décompte, sinon la
   liste dirait deux choses différentes de la même échéance. */
const dansNJours = (n, langue) => new Intl.DateTimeFormat(
  langue === "fr" ? "fr-FR" : "en-GB", { day: "numeric", month: "short" }
).format(new Date(Date.now() + n * 86400000));

export const PROCHES_LONG = [...PROCHES, ...[
  { id: "p0", nom: "Adama Traoré", type: "anniversaire",
    jours: 4, notes: 0 },
  { id: "p1", nom: "Alix Ferrand", type: "mariage",
    jours: 5, notes: 3 },
  { id: "p2", nom: "Amina Cissé", type: "retraite",
    jours: 6, notes: 6 },
  { id: "p3", nom: "Anouk Vidal", type: "etape",
    jours: 44, notes: 9 },
  { id: "p4", nom: "Bintou Camara", type: "fete",
    jours: 52, notes: 0 },
  { id: "p5", nom: "Boris Lemoine", type: "anniversaire",
    jours: null, notes: 3 },
  { id: "p6", nom: "Camille Roux", type: "mariage",
    jours: 68, notes: 6 },
  { id: "p7", nom: "Chloé Marchand", type: "retraite",
    jours: 76, notes: 9 },
  { id: "p8", nom: "Dieynaba Ba", type: "etape",
    jours: 84, notes: 0 },
  { id: "p9", nom: "Élise Fontaine", type: "fete",
    jours: 92, notes: 3 },
  { id: "p10", nom: "Émile Garnier", type: "anniversaire",
    jours: 100, notes: 6 },
  { id: "p11", nom: "Fanta Keïta", type: "mariage",
    jours: null, notes: 9 },
  { id: "p12", nom: "Gabriel Léger", type: "retraite",
    jours: 116, notes: 0 },
  { id: "p13", nom: "Hugo Bonnet", type: "etape",
    jours: 124, notes: 3 },
  { id: "p14", nom: "Ibrahima Sarr", type: "fete",
    jours: 132, notes: 6 },
  { id: "p15", nom: "Inès Chevalier", type: "anniversaire",
    jours: 140, notes: 9 },
  { id: "p16", nom: "Jonas Perrin", type: "mariage",
    jours: 148, notes: 0 },
  { id: "p17", nom: "Julie Deschamps", type: "retraite",
    jours: null, notes: 3 },
  { id: "p18", nom: "Karim Belhaj", type: "etape",
    jours: 164, notes: 6 },
  { id: "p19", nom: "Léa Mercier", type: "fete",
    jours: 172, notes: 9 },
  { id: "p20", nom: "Louis Aubert", type: "anniversaire",
    jours: 180, notes: 0 },
  { id: "p21", nom: "Mariam Touré", type: "mariage",
    jours: 188, notes: 3 },
  { id: "p22", nom: "Marius Colin", type: "retraite",
    jours: 196, notes: 6 },
  { id: "p23", nom: "Nadia Haddad", type: "etape",
    jours: null, notes: 9 },
  { id: "p24", nom: "Noé Rousseau", type: "fete",
    jours: 212, notes: 0 },
  { id: "p25", nom: "Océane Bruneau", type: "anniversaire",
    jours: 220, notes: 3 },
  { id: "p26", nom: "Omar Fall", type: "mariage",
    jours: 228, notes: 6 },
  { id: "p27", nom: "Paul Rivière", type: "retraite",
    jours: 236, notes: 9 },
  { id: "p28", nom: "Rachel Abitbol", type: "etape",
    jours: 244, notes: 0 },
  { id: "p29", nom: "Rémi Delaunay", type: "fete",
    jours: null, notes: 3 },
  { id: "p30", nom: "Sarah Nguyen", type: "anniversaire",
    jours: 260, notes: 6 },
  { id: "p31", nom: "Sékou Diallo", type: "mariage",
    jours: 268, notes: 9 },
  { id: "p32", nom: "Simon Lacroix", type: "retraite",
    jours: 276, notes: 0 },
  { id: "p33", nom: "Sofia Moreno", type: "etape",
    jours: 284, notes: 3 },
  { id: "p34", nom: "Tanguy Hervé", type: "fete",
    jours: 292, notes: 6 },
  { id: "p35", nom: "Théo Barbier", type: "anniversaire",
    jours: null, notes: 9 },
  { id: "p36", nom: "Yasmine Oualid", type: "mariage",
    jours: 308, notes: 0 },
  { id: "p37", nom: "Zoé Pelletier", type: "retraite",
    jours: 316, notes: 3 }
].map((p) => p.jours == null ? p : {
  ...p, date: dansNJours(p.jours, "fr"), dateEn: dansNJours(p.jours, "en")
})];
