export const COPY = {
  fr: {
    langue: "fr",

    /* Onglets — ils ont leur propre version, ils ne se traduisent pas mot à mot */

    /* Accueil — la phrase se compose selon la situation, et reste juste
       dans tous les cas. Voir spec 3.2. */
    salut: (prenom) => "Bonjour, " + prenom,
    etatRien: "Rien dans les semaines qui viennent.",
    etatUnAujourdhui: "Une date aujourd'hui.",
    etatUnSemaine: "Une date cette semaine.",
    etatDeuxSemaine: "Deux dates cette semaine.",
    etatPlusieursSemaine: (n) => n + " dates cette semaine.",
    etatUnAujourdhuiEtSemaine: (n) => n === 1
      ? "Une date aujourd'hui, une autre cette semaine."
      : "Une date aujourd'hui, " + n + " autres cette semaine.",
    etatLointain: (date) => "Rien avant le " + date + ".",

    ceQuiApproche: "Ce qui approche",
    preparer: "Préparer",
    marquerEnvoye: "Marquer envoyé",
    laisserNote: "Laisser une note",
    ajouterAnniversaire: "Ajouter un anniversaire",
    voirTout: "Voir tout",

    videCarnetTitre: "Votre carnet est prêt",
    videCarnetTexte: "Ajoutez un premier proche et sa date. Lehno s'occupe de vous le rappeler.",
    videRienTitre: "Rien dans les semaines qui viennent",
    videRienTexte: "Le bon moment pour noter une idée pendant qu'elle est fraîche.",

    /* Proches */
    prochesTitre: "Vos proches",
    rechercher: "Rechercher un proche",
    triDate: "Par date", triDateProche: "au plus proche", triDateLoin: "au plus loin",
    triAlphaAZ: "A–Z", triAlphaZA: "Z–A", triAlpha: "A → Z",
    ajouterProche: "Ajouter un proche",
    completer: "Compléter",
    videAnnuaireTitre: "Personne dans le carnet",
    videAnnuaireTexte: "Ajoutez un proche et sa date. Le reste se remplit au fil de l'année.",

    /* Types d'événement */
    typeAnniversaire: "Anniversaire", typeMariage: "Mariage", typeRetraite: "Retraite",
    typeNaissance: "Naissance", typeEtape: "Étape", typeFete: "Fête", typeAutre: "Autre",
    aujourdhui: "aujourd'hui",

    /* Notes */

    /* Réseau et attente */
    horsConnexion: "Hors connexion. Vos notes et vos dates restent consultables.",
    horsConnexionFile: (n) => n === 1
      ? "Hors connexion. Une action repartira au retour du réseau."
      : "Hors connexion. " + n + " actions repartiront au retour du réseau.",
    chargement: "Chargement",

    /* ─── Connexion (3.1) ─── */
    ongletAccueil: "Accueil", ongletDates: "Dates", ongletProches: "Proches", ongletMoi: "Moi",







    /* ─── Mon Mur côté privé (3.10), profil, réglages, sécurité, aide ─── */
    murPrivAdresse: "lehno.app/valentine",
    murPrivPublie: "Publié",
    murPrivPrive: "Hors ligne",
    murPrivBascule: "Rendre mon Mur public",
    murPrivExpose: "Ce qui est exposé",
    murPrivGouts: "Mes goûts",
    murPrivDate: "Ma date d'anniversaire",
    murPrivSouhaits: "Ma liste de souhaits",
    murPrivMots: "Les mots reçus",
    murPrivMotsCompte: (n) => n === 1 ? "1 mot reçu" : n + " mots reçus",
    murPrivVoir: "Voir ma page",
    murPrivRienExpose: "Choisissez ce que vos proches verront.",
    murPrivAucunMotTitre: "Personne n'a encore écrit",
    murPrivAucunMotTexte: "Les mots que vos proches déposeront s'afficheront ici.",

    profilPhoto: "Changer la photo",
    champPrenom: "Prénom",
    champLangue: "Langue de l'interface",
    profilLangueAide: "Elle change tout de suite.",

    reglagesQuand: "Quand vous prévenir",
    reglagesJ7: "Une semaine avant",
    reglagesJ1: "La veille",
    reglagesJour: "Le jour même",
    reglagesComment: "Par quel moyen",
    reglagesPush: "Notification",
    reglagesEmail: "E-mail",
    reglagesRefus: "Les notifications sont refusées au niveau du téléphone. Les rappels partent par e-mail.",
    reglagesActiver: "Activer dans les réglages du téléphone",

    securiteMoyens: "Vos moyens de connexion",
    securiteAppareils: "Appareils connectés",
    securiteCetAppareil: "Cet appareil",
    securiteDeconnecterTout: "Déconnecter les autres appareils",
    securiteSupprimer: "Supprimer mon compte",
    securiteSupprimerAide: "Vos fiches, vos notes et votre Mur partent avec.",
    securiteInhabituelle: "Une connexion inhabituelle a été détectée le 12 août.",

    paiementAucuneTitre: "Aucune méthode enregistrée",
    paiementAucuneTexte: "Elle s'enregistrera d'elle-même au premier achat.",
    paiementAjouter: "Ajouter une méthode",
    paiementExpire: "Expirée",
    paiementDefaut: "Par défaut",

    aideQuestions: "Questions fréquentes",
    aideContact: "Nous écrire",
    aideNoter: "Noter l'application",
    aideVersion: "Version",

    reservIntro: "Les cadeaux que vous vous êtes réservés sur le Mur de vos proches.",
    reservVideTitre: "Aucune réservation",
    reservVideTexte: "Ce que vous réserverez sur un Mur apparaîtra ici.",
    reservRetire: "Retiré par son propriétaire",
    reservLiberer: "Libérer",

    /* ─── Moi (3.17), crédits (3.9), parrainage ─── */
    feuilleCout: "Coût de l'action",
    feuilleLancer: "Lancer",
    feuilleRecharger: "Recharger",
    feuillePasMaintenant: "Pas maintenant",
    creditUnite: (n) => n + (n <= 1 ? " crédit" : " crédits"),
    creditReste: (n) => "il vous en reste " + n + (n <= 1 ? " crédit" : " crédits"),
    creditDepense: (n) => n + (n <= 1 ? " crédit dépensé" : " crédits dépensés"),
    creditMot: (n) => n <= 1 ? "crédit" : "crédits",
    moiCreditsSection: "Crédits",
    moiPresence: "Ma présence publique",
    moiCompte: "Mon compte",
    moiAide: "Aide",
    moiSolde: "Votre solde",
    moiRecharger: "Recharger",
    moiMonMur: "Mon Mur",
    moiMurVisible: "Visible par toute personne ayant le lien",
    moiMurDesactive: "Rien n'est public pour l'instant",
    moiReservations: "Mes réservations",
    moiProfil: "Mon profil",
    moiSecurite: "Sécurité et connexions",
    moiPaiement: "Méthodes de paiement",
    moiReglages: "Rappels et notifications",
    moiLangue: "Langue",
    moiAideCentre: "Questions et contact",
    moiDeconnexion: "Se déconnecter",

    rechargeTitre: "Combien de crédits ?",
    rechargeIntro: "Un crédit par contenu créé pour vous.",
    rechargeUnite: (n) => n === 1 ? "1 crédit" : n + " crédits",
    rechargeEconomie: (p) => "−" + p + " %",
    rechargeMoyen: "Comment payer",
    rechargeMobile: "Mobile money",
    rechargeCarte: "Carte bancaire",
    rechargePayer: (m) => "Payer " + m,
    rechargeAttenteTitre: "Confirmez sur votre téléphone",
    rechargeAttenteTexte: "Une demande vient de partir. Validez-la, l'écran suivra.",
    rechargeAttenteExpire: "Sans validation, la demande expire d'elle-même.",
    rechargeAttenteFermer: "Fermer",
    rechargeAboutiTitre: "Crédits ajoutés",
    rechargeAboutiTexte: (n) => n + " crédits sont sur votre compte.",
    rechargeEchecTitre: "Le paiement n'a pas abouti",
    rechargeEchecTexte: "Rien n'a été prélevé.",

    parrainageTitre: "Invitez, et gagnez tous les deux",
    parrainageTexte: "Votre code donne 2 crédits à qui s'inscrit, et 2 crédits à vous.",
    parrainageCode: "AWA-2K4",
    parrainagePartager: "Partager mon code",
    parrainageFilleuls: (n) => n === 1 ? "Une personne a utilisé votre code" : n + " personnes ont utilisé votre code",
    parrainageAucun: "Personne encore.",

    /* ─── Fiche d'un proche (3.4) et Dates (3.14) ─── */
    procheNotes: (n) => n === 1 ? "1 note" : n + " notes",
    procheAucuneNote: "Rien de noté encore",
    procheProchaine: (quoi, date) => quoi + " le " + date,
    ficheInterets: "Intérêts et goûts",
    ficheIdees: "Idées cadeaux",
    ficheNogo: "Ce qu'il faut éviter",
    ficheNogoTexte: "Je ne bois pas d'alcool.",
    ficheIdeeTexte: "Valery a parlé d'un moulin à café manuel — le précédent rend l'âme.",
    fichePreparer: (date) => "Préparer le " + date,
    ficheAjouterNote: "Ajouter une note",
    fichePortraits: "Ses portraits",
    ficheCollecte: "Faire compléter la fiche",
    ficheIdentite: "Modifier l'identité",
    datesTitre: "Vos dates", ajouterDate: "Ajouter une date", vueListe: "Liste", vueCalendrier: "Calendrier",
    joursCourts: ["L", "M", "M", "J", "V", "S", "D"],
    calendrierAout: "Août 2026", calendrierRien: "Rien ce jour-là.",
    moisAout: "Août", moisSept: "Septembre",

    /* ─── Lien de collecte (3.20) ─── */
    collecteTitre: "Laissez Valery compléter",
    collecteIntro: "Envoyez ce lien : ce qui en revient passe par votre validation avant d'entrer dans la fiche.",
    collecteLien: "lehno.app/c/8Kd2p",
    collectePartager: "Partager le lien",
    collecteCopier: "Copier le lien",
    collecteRevoquer: "Révoquer le lien",
    collecteReactiver: "Réactiver un lien",
    collecteEtatActif: "Actif",
    collecteEtatRevoque: "Révoqué",
    collecteRecu: (n) => n === 1 ? "Une réponse reçue" : n + " réponses reçues",
    collecteAucune: "Aucune réponse pour l'instant.",
    collecteRevoqueTexte: "Ce lien ne mène plus à rien. Vous pouvez en créer un autre.",

    /* ─── Identité d'un proche (3.18) ─── */
    identiteTitre: "Ce que Lehno doit savoir",
    identiteIntro: "Ces quelques éléments orientent ce que Lehno écrit.",
    champNom: "Nom",
    champLien: "Votre lien",
    champRegistre: "Registre",
    registreAmical: "Amical",
    registreFamilial: "Familial",
    registreRespectueux: "Respectueux",
    registreComplice: "Complice",
    identiteRegistreAide: "Le ton des messages proposés.",
    champLangueProche: "Langue des messages",
    identiteSupprimer: "Supprimer cette fiche",
    identiteSupprimerAide: "Ses notes et ses dates partent avec.",
    enregistrer: "Enregistrer",

    /* ─── Portrait, aperçu et partage (3.22) ─── */
    portraitAValider: "À valider",
    portraitApprouver: "Approuver",
    portraitSignature: "Signature Lehno",
    portraitSignatureAide: "Le logotype en pied de l'image partagée.",
    portraitAucunTitre: "Aucun portrait pour l'instant",
    portraitAucunTexte: "Le premier viendra de ce que vous avez noté.",

    /* ─── Reprises en cours (3.16) ─── */
    reprisesIntro: "Rien ne se perd. Ce que vous avez lancé vous attend ici.",
    reprisesVideTitre: "Tout est traité",
    reprisesVideTexte: "Ce que vous commencerez sans finir vous attendra ici.",
    repriseBrouillon: "Brouillon de message",
    repriseIdees: "Idées de cadeau",
    reprisePortrait: "Portrait",
    repriseDepassee: "La date est passée",
    repriseReprendre: "Reprendre",

    /* ─── Centre de notifications (3.13) ─── */
    notifsTitre: "Ce que Lehno signale",
    notifsToutLu: "Tout marquer comme lu",
    notifsAujourdhui: "Aujourd'hui",
    notifsAvant: "Avant",
    notifsVideTitre: "Rien à signaler",
    notifsVideTexte: "Les rappels et les contributions reçues apparaîtront ici.",
    notifRappel: (qui, j) => "Dans " + j + " jours : " + qui,
    notifAujourdhui: (qui) => "C'est aujourd'hui : " + qui,
    notifContribution: (n) => n === 1
      ? "Une contribution attend votre relecture"
      : n + " contributions attendent votre relecture",
    notifCredits: (n) => n + " crédits ont été ajoutés",
    notifPortrait: (qui) => "Le portrait de " + qui + " est prêt",

    /* ─── À valider (3.8) ─── */
    validerIntro: "Rien de ce qui vient de l'extérieur n'entre dans vos fiches sans votre accord.",
    validerRetenir: "Retenir",
    validerEcarter: "Écarter",
    validerVideTitre: "Tout est traité",
    validerVideTexte: "Ce que vos proches déposeront passera ici avant d'entrer dans leurs fiches.",
    validerPour: (qui) => "Pour " + qui,
    validerSouhait: "Souhait",
    validerGout: "Goût",
    validerVoeu: "Mot reçu",
    validerRetenu: (n) => n === 1 ? "Une contribution retenue." : n + " contributions retenues.",
    validerEcarte: "Contribution écartée.",


    /* ─── Composition du portrait (3.7) ─── */
    compoTitre: "Sur quoi s'appuyer",
    compoMots: "Ce que vos notes disent",
    compoPlage: "Quelles notes retenir",
    compoPlageTout: "Tout l'historique",
    compoPlageAn: "Les douze derniers mois",
    compoPlageOccasion: "Une occasion",
    compoPlageAide: (n) => n + " notes retenues",
    compoTon: "Le ton",
    compoTonAide: "Repris du registre de la fiche.",
    compoLongueur: "La longueur",
    compoCourt: "Court", compoMoyen: "Moyen", compoLong: "Long",
    compoLancer: "Composer le portrait",

    /* ─── L'image du portrait (3.22) ─── */
    portraitPhrase: "« l'année où tu as tout osé »",
    portraitMots: ["musique", "générosité", "rires", "Dakar", "rando", "curieux de tout"],
    portraitPlage: (p) => "D'après " + p,
    portraitEnregistrer: "Enregistrer l'image",
    portraitSurMonMur: "Partager sur mon Mur",
    portraitPartagerDehors: "Partager",
    portraitRetirerDuMur: "Retirer de mon Mur",

    /* ─── Préparation et génération (3.7) ─── */
    prepIntro: "Rien ne part sans vous.",
    prepPortraitTitre: "Un portrait",
    prepPortraitTexte: "Ce qu'il y a à retenir, écrit à partir de vos notes. À garder pour vous ou à partager.",
    prepIdeesTitre: "Des idées de cadeau",
    prepIdeesTexte: "Trois pistes qui lui ressemblent, du gratuit au plus cher.",
    prepMessageTitre: "Un message",
    prepMessageTexte: "Un brouillon dans votre ton, à ajuster avant d'envoyer.",
    prepDeja: "Déjà préparé",
    prepRelancer: "Refaire",
    prepVoir: "Voir",
    prepSensible: "Pas d'idée de cadeau pour une date comme celle-ci. Un mot, si vous le souhaitez.",

    genAttenteTitre: "Lehno écrit",
    genAttenteTexte: "Une minute environ. Vous pouvez fermer : ce sera là à votre retour.",
    genAttenteQuitter: "Faire autre chose en attendant",
    genErreurTitre: "L'écriture n'a pas abouti",
    genErreurTexte: "Votre crédit n'a pas été prélevé.",
    genReessayer: "Réessayer",

    resMessageTitre: "Votre message",
    resIdeesTitre: "Trois idées",
    resAjuster: "Ajuster le texte",
    resEnvoyer: "Envoyer",
    resRegenerer: "Refaire",
    resJeter: "Jeter",
    envoiFait: (qui) => "Message marqué comme envoyé à " + qui + ".",
    envoiRappel: "Vous pourrez revenir dessus depuis la fiche.",


    connexionTitre: "Soyez là le jour J",
    connexionTexte: "Les dates de vos proches, et ce que vous savez d'eux. Le moment venu, vous avez déjà tout pour bien faire.",
    connexionErreur: "On n'a pas pu joindre Google. Les autres voies restent ouvertes.",
    avecGoogle: "Continuer avec Google",
    avecApple: "Continuer avec Apple",
    ou: "ou",
    champEmail: "Votre adresse e-mail",
    champEmailEx: "vous@exemple.fr",
    recevoirCode: "Recevoir un code",
    connexionPiedAvant: "En continuant, vous acceptez les ",
    connexionPiedCgu: "conditions d'utilisation",
    connexionPiedEntre: " et la ",
    connexionPiedConf: "politique de confidentialité",
    connexionPiedApres: ".",

    codeTitre: "Votre code est parti",
    codeTexte: "Regardez votre boîte de réception.",
    codeErreur: "Ce code ne correspond pas. Il vous reste deux essais.",
    codeValidite: (duree) => "Encore " + duree + " pour le saisir.",
    codeExpire: "Ce code a expiré.",
    codeRenvoiAttente: (s) => "Nouveau code possible dans " + s + " s",
    valider: "Valider",
    renvoyerCode: "Renvoyer un code",
    retour: "Retour",
    effacer: "Effacer",

    pseudoTitre: "Choisissez votre pseudo",
    champPseudo: "Pseudo",
    pseudoAdresse: "lehno.app/valentine",
    pseudoPris: "Ce pseudo est pris. « valentine2 » est libre.",
    champParrain: "Code de parrainage (facultatif)",
    parrainValide: "Code valide",
    parrainInvalide: "Code invalide",
    continuer: "Continuer",

    bienvenueTitre: (prenom) => "Bienvenue, " + prenom,
    bienvenueTexte: "Votre carnet est ouvert. De quoi préparer vos premières célébrations : un portrait, des idées de cadeau, un mot juste.",
    bienvenueCadeau: "Cadeau de bienvenue",
    bienvenueParrainage: "Bonus de parrainage",
    bienvenueCredits: (n) => n + (n === 1 ? " crédit" : " crédits"),
    inviterAmi: "Inviter un ami",
    commencer: "Commencer",

    /* ─── Note (3.5) ─── */
    noteLabel: "Ce que vous voulez retenir",
    noteRange: "Rangé dans",
    noteRangement: "Rangement",
    notePourQui: "Pour qui",
    noteAjouterProche: "Ajouter",
    noteSansProche: "Désignez au moins un proche pour enregistrer.",
    noteOccasion: "À quelle occasion",
    noteOccasionAide: "Sans occasion, la note décrit le proche et vaut d'une année sur l'autre.",
    noteAjouter: "Ajouter",
    enregistrer: "Enregistrer",

    /* ─── Événement (3.6) ─── */
    evtType: "Type",
    evtAutreType: "Un autre type d'événement",
    evtPourQui: "Pour qui",
    evtCreerProche: "Aucune fiche ne correspond ? Un nom suffit à en créer une.",
    evtDate: "La date",
    evtJour: "Jour", evtMois: "Mois", evtAnnee: "Année",
    evtAnneeAide: "L'année est facultative : un anniversaire se suit sans elle.",
    evtDetails: "Détails",
    evtNature: "Nature",
    evtNatureJoyeux: "Joyeux",
    evtNatureAide: "Une date sensible se détecte, et reste corrigeable.",
    evtRappel: "Rappel",
    evtRappelDefaut: "Une semaine avant",
    evtDejaAnniv: "Valery a déjà un anniversaire au 24 août. Vous modifiez celui-là.",
    sensibleForm: "Une date comme celle-ci se prépare autrement : Lehno n'y proposera pas d'idée de cadeau.",

    /* ─── Recherche (3.15) ─── */
    videRechercheTitre: "Rien sous ce nom",
    videRechercheTexte: "Essayez un prénom, ou ajoutez cette personne.",
    ajouterCeProche: "Ajouter ce proche",

    /* ─── Souhait (3.19) ─── */
    souhaitExemple: "Un moulin à café manuel",
    souhaitAutre: "Un vinyle de Manu Dibango",
    souhaitPrix: "12 000 F",
    souhaitDisponible: "Disponible",
    souhaitReserve: "Réservé",
    souhaitPrecisions: "Précisions",
    souhaitPrecisionsTexte: "Le précédent rend l'âme. Un modèle repéré chez le torréfacteur de Bonapriso.",
    souhaitProvenance: "D'où ça vient",
    souhaitParole: "Valery a parlé d'un moulin à café manuel — le précédent rend l'âme.",
    souhaitOrigine: "noté",
    souhaitOrigineDate: "en mars",
    souhaitReserveTexte: "Awa s'est fait connaître en le réservant.",
    souhaitSurMur: "Exposer sur le Mur",
    souhaitOffert: "Marquer déjà offert",
    souhaitAjouter: "Ajouter",
    modifier: "Modifier",
    videSouhaitsTitre: "Rien de listé pour l'instant",
    videSouhaitsTexte: "Ajoutez une idée, ou partagez un lien de collecte pour la faire remplir.",

    /* ─── Occasion (3.21) ─── */
    occPassee: "Passée",
    occSouhaits: "Liste de souhaits",
    occSansSouhait: "Cette date se prépare sans cadeau.",
    occNotes: "Notes pour cette occasion",
    occNoteTexte: "Prévoir de passer avant midi — l'après-midi, c'est le travail.",
    occNoteDate: "hier",
    occPreparer: "Préparer",
    occIdees: "Trouver des idées",
    occMessage: "Écrire le message",
    occMessageEnvoye: "Message envoyé",
    occMessageTexte: "Valery, 36 ans et toujours cette manie de refaire le monde à minuit.",
    occEnvoyeLe: "envoyé le",
    occVoeuxRecus: "Vœux reçus",
    occAucunVoeu: "Aucun mot pour cette occasion.",
    sensibleApproche: "Le 14 mars approche."
  },

  en: {
    langue: "en",


    salut: (prenom) => "Hi " + prenom,
    etatRien: "Nothing in the coming weeks.",
    etatUnAujourdhui: "One date today.",
    etatUnSemaine: "One date this week.",
    etatDeuxSemaine: "Two dates this week.",
    etatPlusieursSemaine: (n) => n + " dates this week.",
    etatUnAujourdhuiEtSemaine: (n) => n === 1
      ? "One date today, another this week."
      : "One date today, " + n + " more this week.",
    etatLointain: (date) => "Nothing until " + date + ".",

    ceQuiApproche: "Coming up",
    preparer: "Prepare",
    marquerEnvoye: "Mark as sent",
    laisserNote: "Write a note",
    ajouterAnniversaire: "Add a birthday",
    voirTout: "See all",

    videCarnetTitre: "Your notebook is ready",
    videCarnetTexte: "Add someone and their date. Lehno takes care of reminding you.",
    videRienTitre: "Nothing in the coming weeks",
    videRienTexte: "A good moment to note an idea while it's fresh.",

    prochesTitre: "Your people",
    rechercher: "Search for someone",
    triDate: "By date", triDateProche: "soonest first", triDateLoin: "furthest first",
    triAlphaAZ: "A–Z", triAlphaZA: "Z–A", triAlpha: "A → Z",
    ajouterProche: "Add someone",
    completer: "Fill in",
    videAnnuaireTitre: "No one in the notebook yet",
    videAnnuaireTexte: "Add someone and their date. The rest fills up over the year.",

    typeAnniversaire: "Birthday", typeMariage: "Wedding", typeRetraite: "Retirement",
    typeNaissance: "Birth", typeEtape: "Milestone", typeFete: "Celebration", typeAutre: "Other",
    aujourdhui: "today",


    horsConnexion: "Offline. Your notes and dates are still there to read.",
    horsConnexionFile: (n) => n === 1
      ? "Offline. One action will go out when the network is back."
      : "Offline. " + n + " actions will go out when the network is back.",
    chargement: "Loading",

    ongletAccueil: "Home", ongletDates: "Dates", ongletProches: "People", ongletMoi: "Me",






    feuilleCout: "What this costs",
    feuilleLancer: "Start",
    feuilleRecharger: "Top up",
    feuillePasMaintenant: "Not now",
    creditUnite: (n) => n + (n === 1 ? " credit" : " credits"),
    creditReste: (n) => n + (n === 1 ? " credit" : " credits") + " left",
    creditDepense: (n) => n + (n === 1 ? " credit" : " credits") + " spent",
    creditMot: (n) => n === 1 ? "credit" : "credits",

    murPrivAdresse: "lehno.app/valentine",
    murPrivPublie: "Published",
    murPrivPrive: "Offline",
    murPrivBascule: "Make my Wall public",
    murPrivExpose: "What's on show",
    murPrivGouts: "My tastes",
    murPrivDate: "My birthday",
    murPrivSouhaits: "My wishlist",
    murPrivMots: "Notes received",
    murPrivMotsCompte: (n) => n === 1 ? "1 note received" : n + " notes received",
    murPrivVoir: "See my page",
    murPrivRienExpose: "Choose what the people around you will see.",
    murPrivAucunMotTitre: "Nobody has written yet",
    murPrivAucunMotTexte: "Notes left by the people around you will show up here.",

    profilPhoto: "Change photo",
    champPrenom: "First name",
    champLangue: "Interface language",
    profilLangueAide: "It changes right away.",

    reglagesQuand: "When to tell you",
    reglagesJ7: "A week before",
    reglagesJ1: "The day before",
    reglagesJour: "On the day",
    reglagesComment: "How",
    reglagesPush: "Notification",
    reglagesEmail: "Email",
    reglagesRefus: "Notifications are turned off at the phone level. Reminders go out by email.",
    reglagesActiver: "Turn them on in phone settings",

    securiteMoyens: "How you sign in",
    securiteAppareils: "Signed-in devices",
    securiteCetAppareil: "This device",
    securiteDeconnecterTout: "Sign out other devices",
    securiteSupprimer: "Delete my account",
    securiteSupprimerAide: "Your pages, your notes and your Wall go with it.",
    securiteInhabituelle: "An unusual sign-in was detected on 12 August.",

    paiementAucuneTitre: "No method saved",
    paiementAucuneTexte: "One will save itself on your first purchase.",
    paiementAjouter: "Add a method",
    paiementExpire: "Expired",
    paiementDefaut: "Default",

    aideQuestions: "Common questions",
    aideContact: "Write to us",
    aideNoter: "Rate the app",
    aideVersion: "Version",

    reservIntro: "The gifts you reserved on other people's Walls.",
    reservVideTitre: "No reservations",
    reservVideTexte: "Anything you reserve on a Wall will show up here.",
    reservRetire: "Taken down by its owner",
    reservLiberer: "Release",

    moiCreditsSection: "Credits",
    moiPresence: "My public presence",
    moiCompte: "My account",
    moiAide: "Help",
    moiSolde: "Your balance",
    moiRecharger: "Top up",
    moiMonMur: "My Wall",
    moiMurVisible: "Visible to anyone with the link",
    moiMurDesactive: "Nothing is public yet",
    moiReservations: "My reservations",
    moiProfil: "My profile",
    moiSecurite: "Security and sessions",
    moiPaiement: "Payment methods",
    moiReglages: "Reminders and notifications",
    moiLangue: "Language",
    moiAideCentre: "Questions and contact",
    moiDeconnexion: "Sign out",

    rechargeTitre: "How many credits?",
    rechargeIntro: "One credit per piece created for you.",
    rechargeUnite: (n) => n === 1 ? "1 credit" : n + " credits",
    rechargeEconomie: (p) => "−" + p + "%",
    rechargeMoyen: "How to pay",
    rechargeMobile: "Mobile money",
    rechargeCarte: "Card",
    rechargePayer: (m) => "Pay " + m,
    rechargeAttenteTitre: "Confirm on your phone",
    rechargeAttenteTexte: "A request just went out. Approve it and this screen will follow.",
    rechargeAttenteExpire: "Without your approval, the request expires on its own.",
    rechargeAttenteFermer: "Close",
    rechargeAboutiTitre: "Credits added",
    rechargeAboutiTexte: (n) => n + " credits are on your account.",
    rechargeEchecTitre: "The payment didn't go through",
    rechargeEchecTexte: "Nothing was taken.",

    parrainageTitre: "Invite someone, you both gain",
    parrainageTexte: "Your code gives 2 credits to whoever signs up, and 2 credits to you.",
    parrainageCode: "AWA-2K4",
    parrainagePartager: "Share my code",
    parrainageFilleuls: (n) => n === 1 ? "One person used your code" : n + " people used your code",
    parrainageAucun: "Nobody yet.",

    procheNotes: (n) => n === 1 ? "1 note" : n + " notes",
    procheAucuneNote: "Nothing noted yet",
    procheProchaine: (quoi, date) => quoi + " on " + date,
    ficheInterets: "Interests and tastes",
    ficheIdees: "Gift ideas",
    ficheNogo: "What to avoid",
    ficheNogoTexte: "I don't drink alcohol.",
    ficheIdeeTexte: "Valery mentioned a hand coffee grinder — the old one is on its last legs.",
    fichePreparer: (date) => "Prepare for " + date,
    ficheAjouterNote: "Add a note",
    fichePortraits: "Their portraits",
    ficheCollecte: "Have the page filled in",
    ficheIdentite: "Edit details",
    datesTitre: "Your dates", ajouterDate: "Add a date", vueListe: "List", vueCalendrier: "Calendar",
    joursCourts: ["M", "T", "W", "T", "F", "S", "S"],
    calendrierAout: "August 2026", calendrierRien: "Nothing that day.",
    moisAout: "August", moisSept: "September",

    collecteTitre: "Let Valery fill it in",
    collecteIntro: "Send this link: whatever comes back passes through your review before it enters the page.",
    collecteLien: "lehno.app/c/8Kd2p",
    collectePartager: "Share the link",
    collecteCopier: "Copy the link",
    collecteRevoquer: "Revoke the link",
    collecteReactiver: "Create a new link",
    collecteEtatActif: "Active",
    collecteEtatRevoque: "Revoked",
    collecteRecu: (n) => n === 1 ? "One reply received" : n + " replies received",
    collecteAucune: "No replies yet.",
    collecteRevoqueTexte: "This link leads nowhere now. You can create another one.",

    identiteTitre: "What Lehno needs to know",
    identiteIntro: "These few things shape what Lehno writes.",
    champNom: "Name",
    champLien: "How you're related",
    champRegistre: "Register",
    registreAmical: "Friendly",
    registreFamilial: "Family",
    registreRespectueux: "Respectful",
    registreComplice: "Close",
    identiteRegistreAide: "The tone of the drafts.",
    champLangueProche: "Language of messages",
    identiteSupprimer: "Delete this page",
    identiteSupprimerAide: "Its notes and dates go with it.",
    enregistrer: "Save",

    portraitAValider: "To approve",
    portraitApprouver: "Approve",
    portraitSignature: "Lehno signature",
    portraitSignatureAide: "The logotype at the foot of the shared image.",
    portraitAucunTitre: "No portrait yet",
    portraitAucunTexte: "The first one will come from what you noted.",

    reprisesIntro: "Nothing gets lost. What you started is waiting here.",
    reprisesVideTitre: "All caught up",
    reprisesVideTexte: "Anything you start without finishing will wait for you here.",
    repriseBrouillon: "Message draft",
    repriseIdees: "Gift ideas",
    reprisePortrait: "Portrait",
    repriseDepassee: "The date has passed",
    repriseReprendre: "Pick up",

    notifsTitre: "What Lehno flags",
    notifsToutLu: "Mark all as read",
    notifsAujourdhui: "Today",
    notifsAvant: "Earlier",
    notifsVideTitre: "Nothing to flag",
    notifsVideTexte: "Reminders and incoming contributions will show up here.",
    notifRappel: (qui, j) => "In " + j + " days: " + qui,
    notifAujourdhui: (qui) => "Today: " + qui,
    notifContribution: (n) => n === 1
      ? "One contribution is waiting for your review"
      : n + " contributions are waiting for your review",
    notifCredits: (n) => n + " credits were added",
    notifPortrait: (qui) => "The portrait of " + qui + " is ready",

    validerIntro: "Nothing from the outside enters your pages without your say.",
    validerRetenir: "Keep",
    validerEcarter: "Set aside",
    validerVideTitre: "All caught up",
    validerVideTexte: "What the people around you send will pass through here first.",
    validerPour: (qui) => "For " + qui,
    validerSouhait: "Wish",
    validerGout: "Taste",
    validerVoeu: "Note received",
    validerRetenu: (n) => n === 1 ? "One contribution kept." : n + " contributions kept.",
    validerEcarte: "Contribution set aside.",


    compoTitre: "What to draw on",
    compoMots: "What your notes say",
    compoPlage: "Which notes to use",
    compoPlageTout: "Everything",
    compoPlageAn: "The last twelve months",
    compoPlageOccasion: "One occasion",
    compoPlageAide: (n) => n + " notes used",
    compoTon: "The tone",
    compoTonAide: "Taken from the register on their page.",
    compoLongueur: "The length",
    compoCourt: "Short", compoMoyen: "Medium", compoLong: "Long",
    compoLancer: "Compose the portrait",

    portraitPhrase: "“the year you dared everything”",
    portraitMots: ["music", "generosity", "laughter", "Dakar", "hiking", "curious about everything"],
    portraitPlage: (p) => "From " + p,
    portraitEnregistrer: "Save the image",
    portraitSurMonMur: "Share on my Wall",
    portraitPartagerDehors: "Share",
    portraitRetirerDuMur: "Take it off my Wall",

    prepIntro: "Nothing goes out without you.",
    prepPortraitTitre: "A portrait",
    prepPortraitTexte: "What's worth remembering, written from your notes. Keep it or share it.",
    prepIdeesTitre: "Gift ideas",
    prepIdeesTexte: "Three directions that look like them, from free to pricier.",
    prepMessageTitre: "A message",
    prepMessageTexte: "A draft in your voice, to adjust before sending.",
    prepDeja: "Already prepared",
    prepRelancer: "Redo",
    prepVoir: "See",
    prepSensible: "No gift ideas for a date like this one. A few words, if you want them.",

    genAttenteTitre: "Lehno is writing",
    genAttenteTexte: "About a minute. You can close this: it will be here when you come back.",
    genAttenteQuitter: "Do something else meanwhile",
    genErreurTitre: "The writing didn't go through",
    genErreurTexte: "Your credit wasn't taken.",
    genReessayer: "Try again",

    resMessageTitre: "Your message",
    resIdeesTitre: "Three ideas",
    resAjuster: "Adjust the text",
    resEnvoyer: "Send",
    resRegenerer: "Redo",
    resJeter: "Discard",
    envoiFait: (qui) => "Message marked as sent to " + qui + ".",
    envoiRappel: "You can come back to it from their page.",


    connexionTitre: "Be there on the day",
    connexionTexte: "The dates of the people you love, and what you know about them. When the day comes, you already have what you need.",
    connexionErreur: "We couldn't reach Google. The other ways are still open.",
    avecGoogle: "Continue with Google",
    avecApple: "Continue with Apple",
    ou: "or",
    champEmail: "Your email address",
    champEmailEx: "you@example.com",
    recevoirCode: "Send me a code",
    connexionPiedAvant: "By continuing, you agree to the ",
    connexionPiedCgu: "terms of use",
    connexionPiedEntre: " and the ",
    connexionPiedConf: "privacy policy",
    connexionPiedApres: ".",

    codeTitre: "Your code is on its way",
    codeTexte: "Check your inbox.",
    codeErreur: "That code doesn't match. Two tries left.",
    codeValidite: (duree) => duree + " left to enter it.",
    codeExpire: "This code has expired.",
    codeRenvoiAttente: (s) => "New code in " + s + "s",
    valider: "Confirm",
    renvoyerCode: "Send another code",
    retour: "Back",
    effacer: "Clear",

    pseudoTitre: "Pick your handle",
    champPseudo: "Handle",
    pseudoAdresse: "lehno.app/valentine",
    pseudoPris: "That one's taken. \u201Cvalentine2\u201D is free.",
    champParrain: "Referral code (optional)",
    parrainValide: "Valid code",
    parrainInvalide: "Invalid code",
    continuer: "Continue",

    bienvenueTitre: (prenom) => "Welcome, " + prenom,
    bienvenueTexte: "Your notebook is open. Enough to prepare your first celebrations: a portrait, gift ideas, the right words.",
    bienvenueCadeau: "Welcome gift",
    bienvenueParrainage: "Referral bonus",
    bienvenueCredits: (n) => n + (n === 1 ? " credit" : " credits"),
    inviterAmi: "Invite a friend",
    commencer: "Get started",

    noteLabel: "What you want to remember",
    noteRange: "Filed under",
    noteRangement: "Filing",
    notePourQui: "About whom",
    noteAjouterProche: "Add",
    noteSansProche: "Name at least one person to save this.",
    noteOccasion: "For which occasion",
    noteOccasionAide: "With no occasion, the note describes the person and keeps working year after year.",
    noteAjouter: "Add",
    enregistrer: "Save",

    evtType: "Type",
    evtAutreType: "Another kind of event",
    evtPourQui: "About whom",
    evtCreerProche: "No match? A name is enough to create one.",
    evtDate: "The date",
    evtJour: "Day", evtMois: "Month", evtAnnee: "Year",
    evtAnneeAide: "The year is optional — a birthday works without it.",
    evtDetails: "Details",
    evtNature: "Nature",
    evtNatureJoyeux: "Joyful",
    evtNatureAide: "A sensitive date is detected, and stays editable.",
    evtRappel: "Reminder",
    evtRappelDefaut: "One week before",
    evtDejaAnniv: "Valery already has a birthday on 24 Aug. You're editing that one.",
    sensibleForm: "A date like this one is prepared differently: Lehno won't suggest gift ideas for it.",

    videRechercheTitre: "Nothing under that name",
    videRechercheTexte: "Try a first name, or add this person.",
    ajouterCeProche: "Add this person",

    souhaitExemple: "A hand coffee grinder",
    souhaitAutre: "A Manu Dibango record",
    souhaitPrix: "12,000 F",
    souhaitDisponible: "Available",
    souhaitReserve: "Reserved",
    souhaitPrecisions: "Details",
    souhaitPrecisionsTexte: "The old one is on its last legs. A model spotted at the roaster in Bonapriso.",
    souhaitProvenance: "Where this came from",
    souhaitParole: "Valery mentioned a hand coffee grinder — the old one is on its last legs.",
    souhaitOrigine: "noted",
    souhaitOrigineDate: "in March",
    souhaitReserveTexte: "Awa let you know she reserved it.",
    souhaitSurMur: "Show on my Wall",
    souhaitOffert: "Mark as already given",
    souhaitAjouter: "Add",
    modifier: "Edit",
    videSouhaitsTitre: "Nothing listed yet",
    videSouhaitsTexte: "Add an idea, or ask him to fill it in himself.",

    occPassee: "Past",
    occSouhaits: "Wishlist",
    occSansSouhait: "This date is prepared without a gift.",
    occNotes: "Notes for this occasion",
    occNoteTexte: "Go before noon — he works in the afternoon.",
    occNoteDate: "yesterday",
    occPreparer: "Prepare",
    occIdees: "Find some ideas",
    occMessage: "Write the message",
    occMessageEnvoye: "Message sent",
    occMessageTexte: "Valery, 36 and still that habit of fixing the world at midnight.",
    occEnvoyeLe: "sent on",
    occVoeuxRecus: "Wishes received",
    occAucunVoeu: "No words for this occasion.",
    sensibleApproche: "14 March is coming up."
  }
};

/* Les données d'exemple — les mêmes personnes partout, comme validé. */
export const PROCHES = [
  { id: "awa", nom: "Awa Diop", type: "anniversaire", date: "22 août", dateEn: "22 Aug",
    precision: "36 ans", precisionEn: "36 years", jours: 0, notes: 3,
    note: "Awa a parlé d'un cours de céramique, tout près d'ici.",
    noteEn: "Awa mentioned a ceramics class, right nearby.",
    noteOrigine: "noté", noteOrigineEn: "noted", noteDate: "en mars", noteDateEn: "in March" },
  { id: "valery", nom: "Valery Bah", type: "anniversaire", date: "24 août", dateEn: "24 Aug",
    precision: "36 ans", precisionEn: "36 years", jours: 3, notes: 9 },
  { id: "mathias", nom: "Mathias & Rose", type: "mariage", date: "30 août", dateEn: "30 Aug",
    precision: "5 ans", precisionEn: "5 years", jours: 9, notes: 2 },
  { id: "maman", nom: "Maman", type: "retraite", date: "2 sept.", dateEn: "2 Sep",
    jours: 12, notes: 14 },
  { id: "nour", nom: "Nour & moi", nomEn: "Nour & me", type: "etape", date: "14 sept.", dateEn: "14 Sep",
    precision: "Six mois", precisionEn: "Six months", jours: 24, notes: 6 }
];
