-- Les motifs alignés sur le kit de back-office du 29 août.
--
-- DEUX JEUX DE CODES COEXISTAIENT, et aucun ne recouvrait l'autre : le kit les
-- tirait du français (`abus_constate`), la semence de l'anglais
-- (`abuse_found`). Zéro code en commun sur cent un — un écran branché aurait
-- reçu « ce motif ne se propose plus pour ce geste » à chaque geste.
--
-- L'anglais l'emporte, et pas sur le fond : le dépôt n'a AUCUN identifiant
-- français — `signup_grant`, `payment_channel`, `user_status_update`. Cent
-- codes français y créeraient une base à deux vocabulaires, où il faudrait
-- deviner identifiant par identifiant dans quelle langue il a été écrit.
--
-- Les libellés, eux, sont ceux du designer, dans les deux langues, sans
-- réécriture. Vingt-quatre motifs entrent : ils viennent des écrans ajoutés
-- depuis — les productions du studio, les réclamations sur un portrait, le
-- retrait d'une ambiance, le versement d'un remboursement.

SELECT set_config('app.reason', 'migration', true);

-- Les motifs, mis au jeu du kit de back-office du 29 août.
INSERT INTO "audit_reason" ("code", "label_fr", "label_en") VALUES
  ('abuse_found', 'Abus constaté', 'Abuse found'),
  ('access_compromised', 'Accès compromis', 'Access compromised'),
  ('access_from_an_unusual_place', 'Accès depuis un lieu inhabituel', 'Access from an unusual place'),
  ('accounts_on_the_same_device', 'Comptes liés au même appareil', 'Accounts on the same device'),
  ('acquisition_campaign', 'Campagne d''acquisition', 'Acquisition campaign'),
  ('age_verified_another_way', 'Ancienneté vérifiée autrement', 'Age verified another way'),
  ('aligning_with_the_brand_s_tone', 'Alignement sur le ton de la marque', 'Aligning with the brand''s tone'),
  ('back_after_a_trial', 'Retour après essai', 'Back after a trial'),
  ('back_on_the_team', 'Retour dans l''équipe', 'Back on the team'),
  ('back_to_normal', 'Retour à la normale', 'Back to normal'),
  ('backup_on_finances', 'Renfort sur les finances', 'Backup on finances'),
  ('campaign_over', 'Campagne terminée', 'Campaign over'),
  ('change_of_post', 'Changement de poste', 'Change of post'),
  ('charged_twice', 'Débit compté deux fois', 'Charged twice'),
  ('code_spread_off_target', 'Code diffusé hors cible', 'Code spread off-target'),
  ('content_complies', 'Contenu conforme', 'Content complies'),
  ('contract_ended', 'Fin de contrat', 'Contract ended'),
  ('correcting_a_grant', 'Correction d''un octroi', 'Correcting a grant'),
  ('cost_too_high', 'Coût trop élevé', 'Cost too high'),
  ('deletion_triggered_by_mistake', 'Suppression déclenchée par erreur', 'Deletion triggered by mistake'),
  ('device_lost', 'Appareil perdu', 'Device lost'),
  ('disabled_by_mistake', 'Erreur de désactivation', 'Disabled by mistake'),
  ('disputed_purchase', 'Achat contesté', 'Disputed purchase'),
  ('duplicate', 'Doublon', 'Duplicate'),
  ('duplicate_payment', 'Double paiement', 'Duplicate payment'),
  ('end_of_on_call', 'Fin d''astreinte', 'End of on-call'),
  ('explicit_request_from_the_holder', 'Demande explicite du titulaire', 'Explicit request from the holder'),
  ('failed_generation', 'Génération échouée', 'Failed generation'),
  ('failure_rate_too_high', 'Taux d''échec trop haut', 'Failure rate too high'),
  ('fixing_an_error', 'Correction d''une erreur', 'Fixing an error'),
  ('generation_not_refunded', 'Génération non recréditée', 'Generation not refunded'),
  ('goodwill', 'Geste commercial', 'Goodwill'),
  ('handed_over_in_person', 'Remis en main propre', 'Handed over in person'),
  ('hateful_speech', 'Propos haineux', 'Hateful speech'),
  ('holder_s_request', 'Demande du titulaire', 'Holder''s request'),
  ('impersonation', 'Usurpation d''identité', 'Impersonation'),
  ('information_about_a_hidden_item', 'Information sur un masquage', 'Information about a hidden item'),
  ('inquiry_closed', 'Enquête close', 'Inquiry closed'),
  ('instruction_to_rewrite', 'Consigne à réécrire', 'Instruction to rewrite'),
  ('internal_report', 'Signalement interne', 'Internal report'),
  ('left_the_team', 'Départ de l''équipe', 'Left the team'),
  ('legal_obligation', 'Obligation légale', 'Legal obligation'),
  ('link_spread_outside_the_circle', 'Lien diffusé hors du cercle', 'Link spread outside the circle'),
  ('load_test', 'Test de charge', 'Load test'),
  ('margin_decision', 'Arbitrage de marge', 'Margin decision'),
  ('new_contract', 'Nouveau contrat', 'New contract'),
  ('notification_lost', 'Notification perdue', 'Notification lost'),
  ('on_call', 'Astreinte', 'On call'),
  ('operation_seen_at_the_operator', 'Opération vue chez l''opérateur', 'Operation seen at the operator'),
  ('operator_error', 'Erreur de l''opérateur', 'Operator error'),
  ('owner_s_request', 'Demande du propriétaire', 'Owner''s request'),
  ('paid_by_mobile_money', 'Versé par mobile money', 'Paid by mobile money'),
  ('paid_by_transfer', 'Versé par virement', 'Paid by transfer'),
  ('personal_data_exposed', 'Donnée personnelle exposée', 'Personal data exposed'),
  ('pricing_adjustment', 'Ajustement tarifaire', 'Pricing adjustment'),
  ('product_decision', 'Décision produit', 'Product decision'),
  ('production_unusable', 'Production inutilisable', 'Production unusable'),
  ('provider_down', 'Prestataire hors service', 'Provider down'),
  ('provider_incident', 'Incident chez le fournisseur', 'Provider incident'),
  ('pulled_during_an_incident', 'Retiré le temps d''un incident', 'Pulled during an incident'),
  ('reducing_access', 'Réduction des accès', 'Reducing access'),
  ('referee_already_signed_up', 'Filleul déjà inscrit', 'Referee already signed up'),
  ('referral_dispute', 'Litige de parrainage', 'Referral dispute'),
  ('referral_never_completed', 'Parrainage non abouti', 'Referral never completed'),
  ('render_degraded_by_a_fallback', 'Rendu dégradé par un repli', 'Render degraded by a fallback'),
  ('rendering_fixed', 'Rendu corrigé', 'Rendering fixed'),
  ('repeated_reports', 'Signalements répétés', 'Repeated reports'),
  ('replaced_by_another_address', 'Remplacé par une autre adresse', 'Replaced by another address'),
  ('report_without_merit', 'Signalement sans objet', 'Report without merit'),
  ('request_to_comply', 'Demande de mise en conformité', 'Request to comply'),
  ('routine_check', 'Vérification de routine', 'Routine check'),
  ('series_of_refusals', 'Série de refus', 'Series of refusals'),
  ('setup_mistake', 'Erreur de paramétrage', 'Setup mistake'),
  ('sexual_content', 'Contenu sexuel', 'Sexual content'),
  ('support_decision', 'Décision de l''assistance', 'Support decision'),
  ('suspected_fraud', 'Fraude suspectée', 'Suspected fraud'),
  ('suspended_pending_an_inquiry', 'Suspension le temps d''une enquête', 'Suspended pending an inquiry'),
  ('taking_responsibility', 'Prise de responsabilité', 'Taking responsibility'),
  ('test_account', 'Compte de test', 'Test account'),
  ('the_account_gives_up_on_the_portrait', 'Le compte renonce au portrait', 'The account gives up on the portrait'),
  ('the_holder_waived_it', 'Le titulaire y a renoncé', 'The holder waived it'),
  ('the_message_is_off_the_requested_tone', 'Le message est hors du ton demandé', 'The message is off the requested tone'),
  ('the_occasion_was_cancelled', 'L''occasion a été annulée', 'The occasion was cancelled'),
  ('the_page_is_gone', 'La page n''existe plus', 'The page is gone'),
  ('the_portrait_does_not_look_like_them', 'Le portrait ne ressemble pas', 'The portrait does not look like them'),
  ('the_same_turns_of_phrase_kept_coming_back', 'Les formules revenaient d''un portrait à l''autre', 'The same turns of phrase kept coming back'),
  ('the_tone_was_too_cold', 'Le ton était trop froid', 'The tone was too cold'),
  ('the_tone_was_too_familiar', 'Le ton était trop familier', 'The tone was too familiar'),
  ('third_party_report', 'Signalement d''un tiers', 'Third-party report'),
  ('too_little_use', 'Usage trop faible', 'Too little use'),
  ('tool_error', 'Erreur de l''outil', 'Tool error'),
  ('unknown_account_targeted', 'Compte inconnu visé', 'Unknown account targeted'),
  ('unlawful_content', 'Contenu illicite', 'Unlawful content'),
  ('unsatisfying_result', 'Rendu insatisfaisant', 'Unsatisfying result'),
  ('unusual_access', 'Accès inhabituel', 'Unusual access'),
  ('unusually_long_wait', 'Attente anormalement longue', 'Unusually long wait'),
  ('user_feedback', 'Retour des utilisateurs', 'User feedback'),
  ('user_identified', 'Utilisateur identifié', 'User identified'),
  ('users_asked_for_it', 'Demande des utilisateurs', 'Users asked for it'),
  ('warning', 'Avertissement', 'Warning'),
  ('wrong_first_name', 'Erreur sur le prénom', 'Wrong first name')
ON CONFLICT ("code") DO UPDATE SET "label_fr" = EXCLUDED."label_fr", "label_en" = EXCLUDED."label_en";

DELETE FROM "audit_reason_scope";
INSERT INTO "audit_reason_scope" ("reason_id", "geste", "position")
SELECT r.id, v.geste, v.position FROM (VALUES
  ('abuse_found', 'promo_code_disable', 2),
  ('access_compromised', 'admin_deactivate', 1),
  ('access_from_an_unusual_place', 'login_incident_close', 1),
  ('accounts_on_the_same_device', 'referral_correct', 0),
  ('acquisition_campaign', 'parameter_update', 1),
  ('age_verified_another_way', 'refund_block_lift', 1),
  ('aligning_with_the_brand_s_tone', 'studio_ambiance_retone', 3),
  ('back_after_a_trial', 'studio_option_enable', 2),
  ('back_on_the_team', 'admin_reactivate', 0),
  ('back_to_normal', 'ai_model_enable', 0),
  ('backup_on_finances', 'admin_promote', 1),
  ('campaign_over', 'promo_code_disable', 0),
  ('change_of_post', 'admin_demote', 0),
  ('charged_twice', 'portrait_refund', 1),
  ('code_spread_off_target', 'promo_code_disable', 1),
  ('content_complies', 'moderation_dismiss', 1),
  ('contract_ended', 'ai_model_disable', 3),
  ('correcting_a_grant', 'credit_adjust', 4),
  ('cost_too_high', 'ai_model_disable', 1),
  ('deletion_triggered_by_mistake', 'deletion_cancel', 1),
  ('device_lost', 'admin_session_close', 0),
  ('disabled_by_mistake', 'admin_reactivate', 2),
  ('disputed_purchase', 'payment_refund', 1),
  ('duplicate', 'moderation_dismiss', 2),
  ('duplicate_payment', 'payment_refund', 0),
  ('end_of_on_call', 'admin_demote', 2),
  ('end_of_on_call', 'admin_session_close', 2),
  ('explicit_request_from_the_holder', 'account_erase', 0),
  ('failed_generation', 'credit_adjust', 0),
  ('failure_rate_too_high', 'ai_model_disable', 0),
  ('fixing_an_error', 'credit_adjust', 2),
  ('fixing_an_error', 'parameter_update', 2),
  ('generation_not_refunded', 'credit_adjust', 1),
  ('goodwill', 'credit_adjust', 1),
  ('goodwill', 'payment_refund', 3),
  ('goodwill', 'portrait_redo', 4),
  ('handed_over_in_person', 'refund_settle', 2),
  ('hateful_speech', 'moderation_hide', 0),
  ('holder_s_request', 'account_suspend', 2),
  ('holder_s_request', 'credit_adjust', 0),
  ('holder_s_request', 'deletion_cancel', 0),
  ('impersonation', 'moderation_revoke_link', 1),
  ('information_about_a_hidden_item', 'moderation_notify', 0),
  ('inquiry_closed', 'admin_reactivate', 1),
  ('instruction_to_rewrite', 'studio_option_disable', 2),
  ('internal_report', 'login_incident_close', 3),
  ('left_the_team', 'admin_deactivate', 0),
  ('legal_obligation', 'account_erase', 2),
  ('link_spread_outside_the_circle', 'moderation_revoke_link', 0),
  ('load_test', 'ai_model_enable', 2),
  ('margin_decision', 'parameter_update', 3),
  ('new_contract', 'ai_model_enable', 1),
  ('notification_lost', 'payment_confirm', 1),
  ('on_call', 'admin_promote', 2),
  ('operation_seen_at_the_operator', 'payment_confirm', 0),
  ('operator_error', 'payment_refund', 2),
  ('owner_s_request', 'moderation_disable', 2),
  ('owner_s_request', 'moderation_revoke_link', 2),
  ('paid_by_mobile_money', 'refund_settle', 0),
  ('paid_by_transfer', 'refund_settle', 1),
  ('personal_data_exposed', 'moderation_hide', 3),
  ('pricing_adjustment', 'parameter_update', 0),
  ('product_decision', 'studio_option_disable', 3),
  ('production_unusable', 'portrait_refund', 0),
  ('provider_down', 'payment_confirm', 2),
  ('provider_incident', 'ai_model_disable', 2),
  ('pulled_during_an_incident', 'external_link_remove', 2),
  ('reducing_access', 'admin_demote', 1),
  ('referee_already_signed_up', 'referral_correct', 1),
  ('referral_dispute', 'credit_adjust', 5),
  ('referral_never_completed', 'referral_correct', 2),
  ('render_degraded_by_a_fallback', 'portrait_redo', 3),
  ('rendering_fixed', 'studio_option_enable', 0),
  ('repeated_reports', 'moderation_disable', 0),
  ('replaced_by_another_address', 'external_link_remove', 1),
  ('report_without_merit', 'moderation_dismiss', 0),
  ('request_to_comply', 'moderation_notify', 1),
  ('routine_check', 'payment_chase', 1),
  ('series_of_refusals', 'login_incident_close', 0),
  ('setup_mistake', 'promo_code_disable', 3),
  ('sexual_content', 'moderation_hide', 1),
  ('support_decision', 'refund_block_lift', 2),
  ('suspected_fraud', 'account_suspend', 1),
  ('suspended_pending_an_inquiry', 'admin_deactivate', 2),
  ('taking_responsibility', 'admin_promote', 0),
  ('test_account', 'account_erase', 1),
  ('the_account_gives_up_on_the_portrait', 'portrait_refund', 3),
  ('the_holder_waived_it', 'refund_settle', 3),
  ('the_message_is_off_the_requested_tone', 'portrait_redo', 1),
  ('the_occasion_was_cancelled', 'portrait_refund', 2),
  ('the_page_is_gone', 'external_link_remove', 0),
  ('the_portrait_does_not_look_like_them', 'portrait_redo', 0),
  ('the_same_turns_of_phrase_kept_coming_back', 'studio_ambiance_retone', 2),
  ('the_tone_was_too_cold', 'studio_ambiance_retone', 1),
  ('the_tone_was_too_familiar', 'studio_ambiance_retone', 0),
  ('third_party_report', 'account_suspend', 0),
  ('too_little_use', 'studio_option_disable', 0),
  ('tool_error', 'referral_correct', 3),
  ('unknown_account_targeted', 'login_incident_close', 2),
  ('unlawful_content', 'moderation_disable', 1),
  ('unlawful_content', 'moderation_hide', 2),
  ('unsatisfying_result', 'studio_option_disable', 1),
  ('unusual_access', 'admin_session_close', 1),
  ('unusually_long_wait', 'payment_chase', 0),
  ('user_feedback', 'studio_ambiance_retone', 4),
  ('user_identified', 'refund_block_lift', 0),
  ('users_asked_for_it', 'studio_option_enable', 1),
  ('warning', 'moderation_notify', 2),
  ('wrong_first_name', 'portrait_redo', 2)
) AS v(code, geste, position)
JOIN "audit_reason" r ON r.code = v.code;

-- Quatre codes de la première semence quittent le jeu : trois sont les
-- doublons anglais qu'on vient de trancher (« Demande du titulaire » s'écrivait
-- `Holder's request` ici et `Account holder's request` là), le quatrième a
-- changé de libellé.
--
-- Ils se RETIRENT, ils ne s'effacent pas — la règle du module, et elle vaut
-- pour une migration comme pour l'écran. Ils n'ont rien justifié à ce jour,
-- donc le retrait ne coûte rien ; c'est le dernier moment où ce sera vrai. Une
-- fois qu'un code aura servi, le retirer sera la seule option, et l'effacer
-- rendrait illisible ce qu'il expliquait.
UPDATE "audit_reason" SET "is_active" = false
WHERE "code" IN (
  'account_holder_s_request',
  'goodwill_gesture',
  'fixing_a_mistake',
  'failed_generation_not_refunded'
);
